/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.eSign.Model
{
    /// <summary>
    /// Defines a billing plan response object.
    /// </summary>
    [DataContract]
    public partial class BillingPlanResponse :  IEquatable<BillingPlanResponse>, IValidatableObject
    {
        public BillingPlanResponse()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingPlanResponse" /> class.
        /// </summary>
        /// <param name="BillingPlan">BillingPlan.</param>
        /// <param name="SuccessorPlans">.</param>
        public BillingPlanResponse(BillingPlan BillingPlan = default(BillingPlan), List<BillingPlan> SuccessorPlans = default(List<BillingPlan>))
        {
            this.BillingPlan = BillingPlan;
            this.SuccessorPlans = SuccessorPlans;
        }
        
        /// <summary>
        /// Gets or Sets BillingPlan
        /// </summary>
        [DataMember(Name="billingPlan", EmitDefaultValue=false)]
        public BillingPlan BillingPlan { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="successorPlans", EmitDefaultValue=false)]
        public List<BillingPlan> SuccessorPlans { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BillingPlanResponse {\n");
            sb.Append("  BillingPlan: ").Append(BillingPlan).Append("\n");
            sb.Append("  SuccessorPlans: ").Append(SuccessorPlans).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as BillingPlanResponse);
        }

        /// <summary>
        /// Returns true if BillingPlanResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of BillingPlanResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BillingPlanResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.BillingPlan == other.BillingPlan ||
                    this.BillingPlan != null &&
                    this.BillingPlan.Equals(other.BillingPlan)
                ) && 
                (
                    this.SuccessorPlans == other.SuccessorPlans ||
                    this.SuccessorPlans != null &&
                    this.SuccessorPlans.SequenceEqual(other.SuccessorPlans)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.BillingPlan != null)
                    hash = hash * 59 + this.BillingPlan.GetHashCode();
                if (this.SuccessorPlans != null)
                    hash = hash * 59 + this.SuccessorPlans.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
