/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.eSign.Model
{
    /// <summary>
    /// PostTransactionsRequest
    /// </summary>
    [DataContract]
    public partial class PostTransactionsRequest :  IEquatable<PostTransactionsRequest>, IValidatableObject
    {
        public PostTransactionsRequest()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PostTransactionsRequest" /> class.
        /// </summary>
        /// <param name="DocumentData">.</param>
        /// <param name="DptName">.</param>
        /// <param name="TransactionName">.</param>
        /// <param name="TransactionTypeName">.</param>
        public PostTransactionsRequest(string DocumentData = default(string), string DptName = default(string), string TransactionName = default(string), string TransactionTypeName = default(string))
        {
            this.DocumentData = DocumentData;
            this.DptName = DptName;
            this.TransactionName = TransactionName;
            this.TransactionTypeName = TransactionTypeName;
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="documentData", EmitDefaultValue=false)]
        public string DocumentData { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="dptName", EmitDefaultValue=false)]
        public string DptName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="transactionName", EmitDefaultValue=false)]
        public string TransactionName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="transactionTypeName", EmitDefaultValue=false)]
        public string TransactionTypeName { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PostTransactionsRequest {\n");
            sb.Append("  DocumentData: ").Append(DocumentData).Append("\n");
            sb.Append("  DptName: ").Append(DptName).Append("\n");
            sb.Append("  TransactionName: ").Append(TransactionName).Append("\n");
            sb.Append("  TransactionTypeName: ").Append(TransactionTypeName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PostTransactionsRequest);
        }

        /// <summary>
        /// Returns true if PostTransactionsRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of PostTransactionsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PostTransactionsRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.DocumentData == other.DocumentData ||
                    this.DocumentData != null &&
                    this.DocumentData.Equals(other.DocumentData)
                ) && 
                (
                    this.DptName == other.DptName ||
                    this.DptName != null &&
                    this.DptName.Equals(other.DptName)
                ) && 
                (
                    this.TransactionName == other.TransactionName ||
                    this.TransactionName != null &&
                    this.TransactionName.Equals(other.TransactionName)
                ) && 
                (
                    this.TransactionTypeName == other.TransactionTypeName ||
                    this.TransactionTypeName != null &&
                    this.TransactionTypeName.Equals(other.TransactionTypeName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.DocumentData != null)
                    hash = hash * 59 + this.DocumentData.GetHashCode();
                if (this.DptName != null)
                    hash = hash * 59 + this.DptName.GetHashCode();
                if (this.TransactionName != null)
                    hash = hash * 59 + this.TransactionName.GetHashCode();
                if (this.TransactionTypeName != null)
                    hash = hash * 59 + this.TransactionTypeName.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
