/*
 * 
 * (c) Copyright Ascensio System SIA 2010-2014
 * 
 * This program is a free software product.
 * You can redistribute it and/or modify it under the terms of the GNU Affero General Public License
 * (AGPL) version 3 as published by the Free Software Foundation. 
 * In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended to the effect 
 * that Ascensio System SIA expressly excludes the warranty of non-infringement of any third-party rights.
 * 
 * This program is distributed WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * For details, see the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
 * 
 * You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.
 * 
 * The interactive user interfaces in modified source and object code versions of the Program 
 * must display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
 * 
 * Pursuant to Section 7(b) of the License you must retain the original Product logo when distributing the program. 
 * Pursuant to Section 7(e) we decline to grant you any rights under trademark law for use of our trademarks.
 * 
 * All the Product's GUI elements, including illustrations and icon sets, as well as technical 
 * writing content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0 International. 
 * See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
 * 
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Projects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GrammaticalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GrammaticalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Projects.Resources.GrammaticalResource", typeof(GrammaticalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actions.
        /// </summary>
        public static string ActionGenitivePlural {
            get {
                return ResourceManager.GetString("ActionGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actions.
        /// </summary>
        public static string ActionGenitiveSingular {
            get {
                return ResourceManager.GetString("ActionGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action.
        /// </summary>
        public static string ActionNominative {
            get {
                return ResourceManager.GetString("ActionNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active tasks.
        /// </summary>
        public static string ActiveTaskGenitivePlural {
            get {
                return ResourceManager.GetString("ActiveTaskGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active tasks.
        /// </summary>
        public static string ActiveTaskGenitiveSingular {
            get {
                return ResourceManager.GetString("ActiveTaskGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active task.
        /// </summary>
        public static string ActiveTaskNominative {
            get {
                return ResourceManager.GetString("ActiveTaskNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed tasks.
        /// </summary>
        public static string ClosedTaskGenitivePlural {
            get {
                return ResourceManager.GetString("ClosedTaskGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed tasks.
        /// </summary>
        public static string ClosedTaskGenitiveSingular {
            get {
                return ResourceManager.GetString("ClosedTaskGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed task.
        /// </summary>
        public static string ClosedTaskNominative {
            get {
                return ResourceManager.GetString("ClosedTaskNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string DayGenitivePlural {
            get {
                return ResourceManager.GetString("DayGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string DayGenitiveSingular {
            get {
                return ResourceManager.GetString("DayGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string DayNominative {
            get {
                return ResourceManager.GetString("DayNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discussions.
        /// </summary>
        public static string DiscussionsGenitivePlural {
            get {
                return ResourceManager.GetString("DiscussionsGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discussions.
        /// </summary>
        public static string DiscussionsGenitiveSingular {
            get {
                return ResourceManager.GetString("DiscussionsGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discussion.
        /// </summary>
        public static string DiscussionsNominative {
            get {
                return ResourceManager.GetString("DiscussionsNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to members.
        /// </summary>
        public static string EmployeesGenitivePlural {
            get {
                return ResourceManager.GetString("EmployeesGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to members.
        /// </summary>
        public static string EmployeesGenitiveSingular {
            get {
                return ResourceManager.GetString("EmployeesGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member.
        /// </summary>
        public static string EmployeesNominative {
            get {
                return ResourceManager.GetString("EmployeesNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue milestones.
        /// </summary>
        public static string LateMilestoneGenitivePlural {
            get {
                return ResourceManager.GetString("LateMilestoneGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue milestones.
        /// </summary>
        public static string LateMilestoneGenitiveSingular {
            get {
                return ResourceManager.GetString("LateMilestoneGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue milestone.
        /// </summary>
        public static string LateMilestoneNominative {
            get {
                return ResourceManager.GetString("LateMilestoneNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones.
        /// </summary>
        public static string MilestoneGenitivePlural {
            get {
                return ResourceManager.GetString("MilestoneGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones.
        /// </summary>
        public static string MilestoneGenitiveSingular {
            get {
                return ResourceManager.GetString("MilestoneGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milestones.
        /// </summary>
        public static string MilestoneLowerCaseGenitivePlural {
            get {
                return ResourceManager.GetString("MilestoneLowerCaseGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milestones.
        /// </summary>
        public static string MilestoneLowerCaseGenitiveSingular {
            get {
                return ResourceManager.GetString("MilestoneLowerCaseGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milestone.
        /// </summary>
        public static string MilestoneLowerCaseNominative {
            get {
                return ResourceManager.GetString("MilestoneLowerCaseNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        public static string MilestoneNominative {
            get {
                return ResourceManager.GetString("MilestoneNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string MonthGenitivePlural {
            get {
                return ResourceManager.GetString("MonthGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string MonthGenitiveSingular {
            get {
                return ResourceManager.GetString("MonthGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string MonthNominative {
            get {
                return ResourceManager.GetString("MonthNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new requests.
        /// </summary>
        public static string NewRequestGenitivePlural {
            get {
                return ResourceManager.GetString("NewRequestGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new requests.
        /// </summary>
        public static string NewRequestGenitiveSingular {
            get {
                return ResourceManager.GetString("NewRequestGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new request.
        /// </summary>
        public static string NewRequestNominative {
            get {
                return ResourceManager.GetString("NewRequestNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string OpenMilestoneGenitivePlural {
            get {
                return ResourceManager.GetString("OpenMilestoneGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string OpenMilestoneGenitiveSingular {
            get {
                return ResourceManager.GetString("OpenMilestoneGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string OpenMilestoneNominative {
            get {
                return ResourceManager.GetString("OpenMilestoneNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string OpenTaskGenitivePlural {
            get {
                return ResourceManager.GetString("OpenTaskGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string OpenTaskGenitiveSingular {
            get {
                return ResourceManager.GetString("OpenTaskGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string OpenTaskNominative {
            get {
                return ResourceManager.GetString("OpenTaskNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string OverdueMilestoneGenitivePlural {
            get {
                return ResourceManager.GetString("OverdueMilestoneGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string OverdueMilestoneGenitiveSingular {
            get {
                return ResourceManager.GetString("OverdueMilestoneGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string OverdueMilestoneNominative {
            get {
                return ResourceManager.GetString("OverdueMilestoneNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string OverdueTaskGenitivePlural {
            get {
                return ResourceManager.GetString("OverdueTaskGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string OverdueTaskGenitiveSingular {
            get {
                return ResourceManager.GetString("OverdueTaskGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string OverdueTaskNominative {
            get {
                return ResourceManager.GetString("OverdueTaskNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to members.
        /// </summary>
        public static string ParticipantGenitivePlural {
            get {
                return ResourceManager.GetString("ParticipantGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to members.
        /// </summary>
        public static string ParticipantGenitiveSingular {
            get {
                return ResourceManager.GetString("ParticipantGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member.
        /// </summary>
        public static string ParticipantNominative {
            get {
                return ResourceManager.GetString("ParticipantNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        public static string TaskGenitivePlural {
            get {
                return ResourceManager.GetString("TaskGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        public static string TaskGenitiveSingular {
            get {
                return ResourceManager.GetString("TaskGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        public static string TaskNominative {
            get {
                return ResourceManager.GetString("TaskNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks not completed.
        /// </summary>
        public static string TaskNotDoneGenitivePlural {
            get {
                return ResourceManager.GetString("TaskNotDoneGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks not completed.
        /// </summary>
        public static string TaskNotDoneGenitiveSingular {
            get {
                return ResourceManager.GetString("TaskNotDoneGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task not completed.
        /// </summary>
        public static string TaskNotDoneNominative {
            get {
                return ResourceManager.GetString("TaskNotDoneNominative", resourceCulture);
            }
        }
    }
}
