//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Projects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MilestoneResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MilestoneResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Projects.Resources.MilestoneResource", typeof(MilestoneResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AddMilestoneButton {
            get {
                return ResourceManager.GetString("AddMilestoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the project.
        /// </summary>
        public static string ChooseProject {
            get {
                return ResourceManager.GetString("ChooseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the responsible.
        /// </summary>
        public static string ChooseResponsible {
            get {
                return ResourceManager.GetString("ChooseResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Milestone.
        /// </summary>
        public static string CloseMilestone {
            get {
                return ResourceManager.GetString("CloseMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string DeadlineInMonth {
            get {
                return ResourceManager.GetString("DeadlineInMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two months.
        /// </summary>
        public static string DeadlineInTwoMonths {
            get {
                return ResourceManager.GetString("DeadlineInTwoMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string DeadlineInWeek {
            get {
                return ResourceManager.GetString("DeadlineInWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Milestone.
        /// </summary>
        public static string DeleteMilestone {
            get {
                return ResourceManager.GetString("DeleteMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the milestone?.
        /// </summary>
        public static string DeleteMilestonePopup {
            get {
                return ResourceManager.GetString("DeleteMilestonePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Milestones.
        /// </summary>
        public static string DeleteMilestones {
            get {
                return ResourceManager.GetString("DeleteMilestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete milestones?.
        /// </summary>
        public static string DeleteMilestonesPopup {
            get {
                return ResourceManager.GetString("DeleteMilestonesPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No milestones matching your filter can be displayed in this section..
        /// </summary>
        public static string DescrEmptyListMilFilter {
            get {
                return ResourceManager.GetString("DescrEmptyListMilFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no milestones matching this filter.
        /// </summary>
        public static string FilterNoMilestones {
            get {
                return ResourceManager.GetString("FilterNoMilestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        public static string Milestone {
            get {
                return ResourceManager.GetString("Milestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string MilestoneDeadline {
            get {
                return ResourceManager.GetString("MilestoneDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No milestones have been planned yet.
        /// </summary>
        public static string MilestoneNotFound_Header {
            get {
                return ResourceManager.GetString("MilestoneNotFound_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones.
        /// </summary>
        public static string Milestones {
            get {
                return ResourceManager.GetString("Milestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones mark the major timestamps in project planning process. Once a milestone is created you can fill it with tasks for all project participants. Plan a milestone and set a due date to make sure that the tasks are completed on time..
        /// </summary>
        public static string MilestonesMarkMajorTimestamps {
            get {
                return ResourceManager.GetString("MilestonesMarkMajorTimestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones mark the major timestamps in project planning process. Once a milestone is created it can be filled with tasks for all project participants..
        /// </summary>
        public static string MilestonesMarkMajorTimestampsVisitor {
            get {
                return ResourceManager.GetString("MilestonesMarkMajorTimestampsVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot close a milestone with open tasks..
        /// </summary>
        public static string NotCloseMilWithActiveTasks {
            get {
                return ResourceManager.GetString("NotCloseMilWithActiveTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        public static string NotifyResponsible {
            get {
                return ResourceManager.GetString("NotifyResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each milestone must have a title.
        /// </summary>
        public static string NoTitleMessage {
            get {
                return ResourceManager.GetString("NoTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string Overdue {
            get {
                return ResourceManager.GetString("Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan the first milestone.
        /// </summary>
        public static string PlanFirstMilestone {
            get {
                return ResourceManager.GetString("PlanFirstMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me 48 hours before the due date.
        /// </summary>
        public static string RemindMe {
            get {
                return ResourceManager.GetString("RemindMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key milestone.
        /// </summary>
        public static string RootMilestone {
            get {
                return ResourceManager.GetString("RootMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
