/*
 *
 * (c) Copyright Ascensio System Limited 2010-2016
 *
 * This program is freeware. You can redistribute it and/or modify it under the terms of the GNU 
 * General Public License (GPL) version 3 as published by the Free Software Foundation (https://www.gnu.org/copyleft/gpl.html). 
 * In accordance with Section 7(a) of the GNU GPL its Section 15 shall be amended to the effect that 
 * Ascensio System SIA expressly excludes the warranty of non-infringement of any third-party rights.
 *
 * THIS PROGRAM IS DISTRIBUTED WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF MERCHANTABILITY OR
 * FITNESS FOR A PARTICULAR PURPOSE. For more details, see GNU GPL at https://www.gnu.org/copyleft/gpl.html
 *
 * You can contact Ascensio System SIA by email at sales@onlyoffice.com
 *
 * The interactive user interfaces in modified source and object code versions of ONLYOFFICE must display 
 * Appropriate Legal Notices, as required under Section 5 of the GNU GPL version 3.
 *
 * Pursuant to Section 7 § 3(b) of the GNU GPL you must retain the original ONLYOFFICE logo which contains 
 * relevant author attributions when distributing the software. If the display of the logo in its graphic 
 * form is not reasonably feasible for technical reasons, you must include the words "Powered by ONLYOFFICE" 
 * in every copy of the program you distribute. 
 * Pursuant to Section 7 § 3(e) we decline to grant you any rights under trademark law for use of our trademarks.
 *
*/


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Projects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectTemplatesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectTemplatesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Projects.Resources.ProjectTemplatesResource", typeof(ProjectTemplatesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Milestone.
        /// </summary>
        public static string AddMilestone {
            get {
                return ResourceManager.GetString("AddMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Milestone Title.
        /// </summary>
        public static string AddMilestoneTitle {
            get {
                return ResourceManager.GetString("AddMilestoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task Title.
        /// </summary>
        public static string AddTaskTitle {
            get {
                return ResourceManager.GetString("AddTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Project Templates.
        /// </summary>
        public static string AllProjectTmpl {
            get {
                return ResourceManager.GetString("AllProjectTmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Responsible.
        /// </summary>
        public static string ChooseResponsible {
            get {
                return ResourceManager.GetString("ChooseResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project Template.
        /// </summary>
        public static string CreateProjTmpl {
            get {
                return ResourceManager.GetString("CreateProjTmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create from Template - {0}.
        /// </summary>
        public static string DefaultProjTitle {
            get {
                return ResourceManager.GetString("DefaultProjTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project Structure.
        /// </summary>
        public static string EditProjStructure {
            get {
                return ResourceManager.GetString("EditProjStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project Template.
        /// </summary>
        public static string EditProjTmpl {
            get {
                return ResourceManager.GetString("EditProjTmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the First Template.
        /// </summary>
        public static string EmptyListTemplateButton {
            get {
                return ResourceManager.GetString("EmptyListTemplateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project templates help you create similar projects with associated stuff like building a project team, planning milestones, tasks and discussions saving time spent each time on entering the same data..
        /// </summary>
        public static string EmptyListTemplateDescr {
            get {
                return ResourceManager.GetString("EmptyListTemplateDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no project templates.
        /// </summary>
        public static string EmptyListTemplateHeader {
            get {
                return ResourceManager.GetString("EmptyListTemplateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone have to be named!.
        /// </summary>
        public static string MilestoneError {
            get {
                return ResourceManager.GetString("MilestoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milestones.
        /// </summary>
        public static string Milestones {
            get {
                return ResourceManager.GetString("Milestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody.
        /// </summary>
        public static string NoResponsible {
            get {
                return ResourceManager.GetString("NoResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this template?.
        /// </summary>
        public static string RemoveQuestion {
            get {
                return ResourceManager.GetString("RemoveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Template.
        /// </summary>
        public static string RemoveTemplateTitlePopup {
            get {
                return ResourceManager.GetString("RemoveTemplateTitlePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Create project .
        /// </summary>
        public static string SaveAndCreateProjFromTmpl {
            get {
                return ResourceManager.GetString("SaveAndCreateProjFromTmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Template.
        /// </summary>
        public static string SaveTemplate {
            get {
                return ResourceManager.GetString("SaveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task have to be named!.
        /// </summary>
        public static string TaskError {
            get {
                return ResourceManager.GetString("TaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks without milestone.
        /// </summary>
        public static string TasksWithoutMilestone {
            get {
                return ResourceManager.GetString("TasksWithoutMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TemplateTitle {
            get {
                return ResourceManager.GetString("TemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each template must have a title.
        /// </summary>
        public static string TitleErrorTemplate {
            get {
                return ResourceManager.GetString("TitleErrorTemplate", resourceCulture);
            }
        }
    }
}
