/*
(c) Copyright Ascensio System SIA 2010-2014

This program is a free software product.
You can redistribute it and/or modify it under the terms 
of the GNU Affero General Public License (AGPL) version 3 as published by the Free Software
Foundation. In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended
to the effect that Ascensio System SIA expressly excludes the warranty of non-infringement of 
any third-party rights.

This program is distributed WITHOUT ANY WARRANTY; without even the implied warranty 
of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For details, see 
the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html

You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.

The  interactive user interfaces in modified source and object code versions of the Program must 
display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
 
Pursuant to Section 7(b) of the License you must retain the original Product logo when 
distributing the program. Pursuant to Section 7(e) we decline to grant you any rights under 
trademark law for use of our trademarks.
 
All the Product's GUI elements, including illustrations and icon sets, as well as technical writing
content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0
International. See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Projects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Projects.Resources.ReportResource", typeof(ReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Tasks.
        /// </summary>
        public static string ActiveTasks {
            get {
                return ResourceManager.GetString("ActiveTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string ActiveTaskStatus {
            get {
                return ResourceManager.GetString("ActiveTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Options.
        /// </summary>
        public static string AdditionalOptions {
            get {
                return ResourceManager.GetString("AdditionalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All project team.
        /// </summary>
        public static string AllPeopleInProject {
            get {
                return ResourceManager.GetString("AllPeopleInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any type.
        /// </summary>
        public static string AnyType {
            get {
                return ResourceManager.GetString("AnyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autogenerating Reports.
        /// </summary>
        public static string AutogenReports {
            get {
                return ResourceManager.GetString("AutogenReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate such report automatically.
        /// </summary>
        public static string AutomaticallyGenerate {
            get {
                return ResourceManager.GetString("AutomaticallyGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating report....
        /// </summary>
        public static string BuildingReport {
            get {
                return ResourceManager.GetString("BuildingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the report filter.
        /// </summary>
        public static string ChangeFilterData {
            get {
                return ResourceManager.GetString("ChangeFilterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change the report settings.
        /// </summary>
        public static string ChangeSettings {
            get {
                return ResourceManager.GetString("ChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline for the next.
        /// </summary>
        public static string ChooseNearestMilestonesTimePeriod {
            get {
                return ResourceManager.GetString("ChooseNearestMilestonesTimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a report type.
        /// </summary>
        public static string ChooseReportType {
            get {
                return ResourceManager.GetString("ChooseReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created over the last.
        /// </summary>
        public static string ChooseTasksTimePeriod {
            get {
                return ResourceManager.GetString("ChooseTasksTimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Template.
        /// </summary>
        public static string ChooseTemplate {
            get {
                return ResourceManager.GetString("ChooseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Period.
        /// </summary>
        public static string ChooseTimeInterval {
            get {
                return ResourceManager.GetString("ChooseTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all templates.
        /// </summary>
        public static string ClearAllTemplates {
            get {
                return ResourceManager.GetString("ClearAllTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear report history.
        /// </summary>
        public static string ClearReportHistory {
            get {
                return ResourceManager.GetString("ClearReportHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to sort by this column.
        /// </summary>
        public static string ClickToSortByThisColumn {
            get {
                return ResourceManager.GetString("ClickToSortByThisColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ClosedTaskStatus {
            get {
                return ResourceManager.GetString("ClosedTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new report.
        /// </summary>
        public static string CreateNewReport {
            get {
                return ResourceManager.GetString("CreateNewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Template.
        /// </summary>
        public static string CrteateTemplate {
            get {
                return ResourceManager.GetString("CrteateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone Deadline.
        /// </summary>
        public static string CsvColumnMilestoneDeadline {
            get {
                return ResourceManager.GetString("CsvColumnMilestoneDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone Status.
        /// </summary>
        public static string CsvColumnMilestoneStatus {
            get {
                return ResourceManager.GetString("CsvColumnMilestoneStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone Title.
        /// </summary>
        public static string CsvColumnMilestoneTitle {
            get {
                return ResourceManager.GetString("CsvColumnMilestoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Title.
        /// </summary>
        public static string CsvColumnProjectjTitle {
            get {
                return ResourceManager.GetString("CsvColumnProjectjTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Due date.
        /// </summary>
        public static string CsvColumnTaskDueDate {
            get {
                return ResourceManager.GetString("CsvColumnTaskDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Status.
        /// </summary>
        public static string CsvColumnTaskStatus {
            get {
                return ResourceManager.GetString("CsvColumnTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Title.
        /// </summary>
        public static string CsvColumnTaskTitle {
            get {
                return ResourceManager.GetString("CsvColumnTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string CsvColumnUserName {
            get {
                return ResourceManager.GetString("CsvColumnUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all autogenerated.
        /// </summary>
        public static string DaleteAllAutogen {
            get {
                return ResourceManager.GetString("DaleteAllAutogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string DeadLine {
            get {
                return ResourceManager.GetString("DeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all templates.
        /// </summary>
        public static string DeleteAllTemplates {
            get {
                return ResourceManager.GetString("DeleteAllTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {!Group}.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Template.
        /// </summary>
        public static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No templates could be found.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to assign a name to the template.
        /// </summary>
        public static string EmptyTemplateTitle {
            get {
                return ResourceManager.GetString("EmptyTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        public static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every month.
        /// </summary>
        public static string EveryMonth {
            get {
                return ResourceManager.GetString("EveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every week.
        /// </summary>
        public static string EveryWeek {
            get {
                return ResourceManager.GetString("EveryWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every year.
        /// </summary>
        public static string EveryYear {
            get {
                return ResourceManager.GetString("EveryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to .csv.
        /// </summary>
        public static string ExportToCSV {
            get {
                return ResourceManager.GetString("ExportToCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show again.
        /// </summary>
        public static string ExportToCSVCheckboxLabel {
            get {
                return ResourceManager.GetString("ExportToCSVCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The generated report will be opened by TeamLab Spreadsheet Editor and saved in the My Documents folder..
        /// </summary>
        public static string ExportToCSVNote {
            get {
                return ResourceManager.GetString("ExportToCSVNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to html.
        /// </summary>
        public static string ExportToHTML {
            get {
                return ResourceManager.GetString("ExportToHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to xml.
        /// </summary>
        public static string ExportToXML {
            get {
                return ResourceManager.GetString("ExportToXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate from Template.
        /// </summary>
        public static string GenerateFromTemplate {
            get {
                return ResourceManager.GetString("GenerateFromTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        public static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation date.
        /// </summary>
        public static string GenerationDate {
            get {
                return ResourceManager.GetString("GenerationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect date range.
        /// </summary>
        public static string IncorrectDateRage {
            get {
                return ResourceManager.GetString("IncorrectDateRage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous week.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous year.
        /// </summary>
        public static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Main Page.
        /// </summary>
        public static string MainReportPage {
            get {
                return ResourceManager.GetString("MainReportPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones Status.
        /// </summary>
        public static string MilestonesStatus {
            get {
                return ResourceManager.GetString("MilestonesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Templates.
        /// </summary>
        public static string MyTemplates {
            get {
                return ResourceManager.GetString("MyTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project contains no milestones and tasks.
        /// </summary>
        public static string NoMilestonesAndTasks {
            get {
                return ResourceManager.GetString("NoMilestonesAndTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or the date planned.
        /// </summary>
        public static string OrThePlannedDate {
            get {
                return ResourceManager.GetString("OrThePlannedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Milestone.
        /// </summary>
        public static string OutOfMilestone {
            get {
                return ResourceManager.GetString("OutOfMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Participiants {
            get {
                return ResourceManager.GetString("Participiants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Statuses.
        /// </summary>
        public static string PaymentStatuses {
            get {
                return ResourceManager.GetString("PaymentStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Those subscribed to report.
        /// </summary>
        public static string PepleSubscribedToReport {
            get {
                return ResourceManager.GetString("PepleSubscribedToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation Time.
        /// </summary>
        public static string PeriodOfGeneration {
            get {
                return ResourceManager.GetString("PeriodOfGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Report.
        /// </summary>
        public static string PrintReport {
            get {
                return ResourceManager.GetString("PrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Status.
        /// </summary>
        public static string ProjectsStatus {
            get {
                return ResourceManager.GetString("ProjectsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Tasks Report.
        /// </summary>
        public static string ReportClosedTasks {
            get {
                return ResourceManager.GetString("ReportClosedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} for the period {2} - {3}.
        /// </summary>
        public static string ReportCompletedTasks_InfoLine {
            get {
                return ResourceManager.GetString("ReportCompletedTasks_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Tasks.
        /// </summary>
        public static string ReportCompletedTasks_Title {
            get {
                return ResourceManager.GetString("ReportCompletedTasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Reports.
        /// </summary>
        public static string ReportDetailed_Title {
            get {
                return ResourceManager.GetString("ReportDetailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}The Users with No Active Tasks report will display a list of the users who have no active tasks at the moment. {3}{2}To view all users with no active tasks across all projects, click on Generate Report right away.{3}{2}To select a particular group or check a particular user, configure the report parameters in the Filter section first, and then click on Generate Report.{3}{1}.
        /// </summary>
        public static string ReportEmployeesWithoutActiveTasks_Description {
            get {
                return ResourceManager.GetString("ReportEmployeesWithoutActiveTasks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} {2}.
        /// </summary>
        public static string ReportEmployeesWithoutActiveTasks_InfoLine {
            get {
                return ResourceManager.GetString("ReportEmployeesWithoutActiveTasks_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {!Users} with no active tasks.
        /// </summary>
        public static string ReportEmployeesWithoutActiveTasks_Title {
            get {
                return ResourceManager.GetString("ReportEmployeesWithoutActiveTasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}The Workload report will display the number of tasks assigned to a user, grouped according to their status.{3}{2}To view the data for all the users, click on Generate Report right away. {3}{2}To select a particular group or user, configure the report parameters in the Filter section first, and then click on Generate Report.{3}{1}.
        /// </summary>
        public static string ReportEmployment_Description {
            get {
                return ResourceManager.GetString("ReportEmployment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} {2}.
        /// </summary>
        public static string ReportEmployment_InfoLine {
            get {
                return ResourceManager.GetString("ReportEmployment_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workload.
        /// </summary>
        public static string ReportEmployment_Title {
            get {
                return ResourceManager.GetString("ReportEmployment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report History.
        /// </summary>
        public static string ReportHistory {
            get {
                return ResourceManager.GetString("ReportHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}The Overdue Milestones report will display a list of overdue milestones.{3}{2}To view the overdue milestones across all projects, click on Generate Report right away.{3}{2}To view the overdue milestones for a given project only, select the desired project from the drop-down list in the Filter section first, and then click on Generate Report.{3}{1}.
        /// </summary>
        public static string ReportLateMilestones_Description {
            get {
                return ResourceManager.GetString("ReportLateMilestones_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} {2}.
        /// </summary>
        public static string ReportLateMilestones_InfoLine {
            get {
                return ResourceManager.GetString("ReportLateMilestones_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue Milestones.
        /// </summary>
        public static string ReportLateMilestones_Title {
            get {
                return ResourceManager.GetString("ReportLateMilestones_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}The Overdue Tasks report will display a list of overdue tasks.{3}{2}To view the overdue tasks across all projects, click the Generate Report link.{3}{2}To view the overdue tasks for a given project only, select the desired project from the dropdown list in the Filter section first, and then click the Generate Report link.{3}{1}.
        /// </summary>
        public static string ReportLateTasks_Description {
            get {
                return ResourceManager.GetString("ReportLateTasks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue Tasks.
        /// </summary>
        public static string ReportLateTasks_Title {
            get {
                return ResourceManager.GetString("ReportLateTasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}The Milestone List report displays the list of milestones grouped according to the project they are attached to. The default report will show the list of all milestones across all projects, with their respective deadlines indicated.{3}{2}To generate a report, click on Generate Report button below.{3}{2}Click on View filters link to change the default report settings. You may select to view only the milestones for a particular project or of a given status. Once the filter is configured, click on Genera [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportMilestoneList_Description {
            get {
                return ResourceManager.GetString("ReportMilestoneList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} {2}.
        /// </summary>
        public static string ReportMilestoneList_InfoLine {
            get {
                return ResourceManager.GetString("ReportMilestoneList_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone List.
        /// </summary>
        public static string ReportMilestoneList_Title {
            get {
                return ResourceManager.GetString("ReportMilestoneList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Name.
        /// </summary>
        public static string ReportName {
            get {
                return ResourceManager.GetString("ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tasks Report.
        /// </summary>
        public static string ReportOpenTasks {
            get {
                return ResourceManager.GetString("ReportOpenTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report «{0}».
        /// </summary>
        public static string ReportPageTitle {
            get {
                return ResourceManager.GetString("ReportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Tracking Reports.
        /// </summary>
        public static string ReportProblemTracking_Title {
            get {
                return ResourceManager.GetString("ReportProblemTracking_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}The Project List report will display a list of projects.{3}{2}To view all active projects with their respective manager, number of tasks, milestones, actions, and team members, click on Generate Report right away.{3}{2}To view projects within a particular group and/or view both active and completed projects, configure the report parameters in the Filter section first, and then click on Generate Report.{3}{1}.
        /// </summary>
        public static string ReportProjectList_Description {
            get {
                return ResourceManager.GetString("ReportProjectList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} {2}.
        /// </summary>
        public static string ReportProjectList_InfoLine {
            get {
                return ResourceManager.GetString("ReportProjectList_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project List.
        /// </summary>
        public static string ReportProjectList_Title {
            get {
                return ResourceManager.GetString("ReportProjectList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}The Projects with No Open Milestones report will display a list of projects with no open milestones attached.{3}{2}To view all projects with no open milestones, click on Generate Report right away.{3}{2}To check such projects within a particular group or check a particular user, select the desired group and/or user in the Filter section first, and then click on Generate Report.{3}{1}.
        /// </summary>
        public static string ReportProjectsWithoutActiveMilestones_Description {
            get {
                return ResourceManager.GetString("ReportProjectsWithoutActiveMilestones_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} {2}.
        /// </summary>
        public static string ReportProjectsWithoutActiveMilestones_InfoLine {
            get {
                return ResourceManager.GetString("ReportProjectsWithoutActiveMilestones_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects with no active milestones.
        /// </summary>
        public static string ReportProjectsWithoutActiveMilestones_Title {
            get {
                return ResourceManager.GetString("ReportProjectsWithoutActiveMilestones_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}The Projects with No Active Tasks report will display a list of projects with no active tasks assigned.{3}{2}To view all projects with no active tasks, click on Generate Report right away.{3}{2}To check such projects within a particular group or check a particular user, select the desired group and/or user in the Filter section first, and then click on Generate Report.{3}{1}.
        /// </summary>
        public static string ReportProjectsWithoutActiveTasks_Description {
            get {
                return ResourceManager.GetString("ReportProjectsWithoutActiveTasks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} {2}.
        /// </summary>
        public static string ReportProjectsWithoutActiveTasks_InfoLine {
            get {
                return ResourceManager.GetString("ReportProjectsWithoutActiveTasks_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects with no active tasks.
        /// </summary>
        public static string ReportProjectsWithoutActiveTasks_Title {
            get {
                return ResourceManager.GetString("ReportProjectsWithoutActiveTasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics Reports.
        /// </summary>
        public static string ReportStatistics_Title {
            get {
                return ResourceManager.GetString("ReportStatistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}The Project Tasks report will display a list of tasks grouped according to the project and milestone they are attached to. {3}{2}To view the list of all tasks across all projects with the responsible party and status indicated, cick on Generate Report right away.{3}{2}To view only the tasks for a particular project or of a given status, configure the report parameters in the Filter section first, and then click on Generate Report.{3}{1}.
        /// </summary>
        public static string ReportTaskList_Description {
            get {
                return ResourceManager.GetString("ReportTaskList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} {2}.
        /// </summary>
        public static string ReportTaskList_InfoLine {
            get {
                return ResourceManager.GetString("ReportTaskList_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Tasks.
        /// </summary>
        public static string ReportTaskList_Title {
            get {
                return ResourceManager.GetString("ReportTaskList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}Time Tracking report is a list of tasks that indicates the actual work time spent by users on their accomplishment basing on a time tracking register.{3}{2}This report allows to track the task progess by the actual time spent on current tasks.{3}{1}.
        /// </summary>
        public static string ReportTimeSpend_Description {
            get {
                return ResourceManager.GetString("ReportTimeSpend_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} for the period {2} - {3}.
        /// </summary>
        public static string ReportTimeSpend_InfoLine {
            get {
                return ResourceManager.GetString("ReportTimeSpend_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Spent.
        /// </summary>
        public static string ReportTimeSpend_Title {
            get {
                return ResourceManager.GetString("ReportTimeSpend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}The Time Tracking Report displays a list of users with their total work time calculated basing on a time register.{3}{2}This report helps track the total amount of time spent by a user on performing his tasks.{3}{1}.
        /// </summary>
        public static string ReportTimeSpendSummary_Description {
            get {
                return ResourceManager.GetString("ReportTimeSpendSummary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} for the period {2} - {3}.
        /// </summary>
        public static string ReportTimeSpendSummary_InfoLine {
            get {
                return ResourceManager.GetString("ReportTimeSpendSummary_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Tracking Report.
        /// </summary>
        public static string ReportTimeSpendSummary_Title {
            get {
                return ResourceManager.GetString("ReportTimeSpendSummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}The Upcoming Milestones report will display a list of upcoming milestones.{3}{2}To view the upcoming milestones across all projects for a week&apos;s period, click on Generate Report right away.{3}{2}To view the upcoming milestones for a given project and/or another time period, select the desired project from the drop-down list and/or set another margin date in the Up to date field first, and then click on Generate Report.{3}{1}.
        /// </summary>
        public static string ReportUpcomingMilestones_Description {
            get {
                return ResourceManager.GetString("ReportUpcomingMilestones_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} {2}.
        /// </summary>
        public static string ReportUpcomingMilestones_InfoLine {
            get {
                return ResourceManager.GetString("ReportUpcomingMilestones_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Milestones.
        /// </summary>
        public static string ReportUpcomingMilestones_Title {
            get {
                return ResourceManager.GetString("ReportUpcomingMilestones_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}The User Activity report will display a particular actions of users inside Projects for a given time period.{3}{2}To display your own activity for the previous week, click on Generate Report right away.{3}{2}To set another time period or select another user, configure the report parameters in the Filter section first, and then click on Generate Report.{3}{1}.
        /// </summary>
        public static string ReportUserActivity_Descripton {
            get {
                return ResourceManager.GetString("ReportUserActivity_Descripton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} {2}.
        /// </summary>
        public static string ReportUserActivity_InfoLine {
            get {
                return ResourceManager.GetString("ReportUserActivity_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Activity.
        /// </summary>
        public static string ReportUserActivity_Title {
            get {
                return ResourceManager.GetString("ReportUserActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}The User Tasks report will display the list of tasks grouped according to the user they are assigned to.{3}{2}To view all tasks of users with their status indicated, click on Generate Report right away.{3}{2}To view only the tasks for a particular project or of a given status, configure the report parameters in the Filter section first, and then click on Generate Report.{3}{1}.
        /// </summary>
        public static string ReportUserTasks_Description {
            get {
                return ResourceManager.GetString("ReportUserTasks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated: {0} {1} {2}.
        /// </summary>
        public static string ReportUserTasks_InfoLine {
            get {
                return ResourceManager.GetString("ReportUserTasks_InfoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Tasks.
        /// </summary>
        public static string ReportUserTasks_Title {
            get {
                return ResourceManager.GetString("ReportUserTasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as template.
        /// </summary>
        public static string SaveAsTemplate {
            get {
                return ResourceManager.GetString("SaveAsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send via e-mail.
        /// </summary>
        public static string SendOnEmail {
            get {
                return ResourceManager.GetString("SendOnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tasks.
        /// </summary>
        public static string ShowTasks {
            get {
                return ResourceManager.GetString("ShowTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show User Activity report.
        /// </summary>
        public static string ShowUserActivityReport {
            get {
                return ResourceManager.GetString("ShowUserActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show User Tasks report.
        /// </summary>
        public static string ShowUserTasksReport {
            get {
                return ResourceManager.GetString("ShowUserTasksReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks completed.
        /// </summary>
        public static string TaskDone {
            get {
                return ResourceManager.GetString("TaskDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Report.
        /// </summary>
        public static string TaskReport {
            get {
                return ResourceManager.GetString("TaskReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Tasks.
        /// </summary>
        public static string TasksDone {
            get {
                return ResourceManager.GetString("TasksDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Status.
        /// </summary>
        public static string TasksStatus {
            get {
                return ResourceManager.GetString("TasksStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks in progress.
        /// </summary>
        public static string TasksWorkingOn {
            get {
                return ResourceManager.GetString("TasksWorkingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template and autogeneration.
        /// </summary>
        public static string TemplateAndAutogen {
            get {
                return ResourceManager.GetString("TemplateAndAutogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It might have been deleted, or there is no template with such ID.
        /// </summary>
        public static string TemplateNotFound_Body {
            get {
                return ResourceManager.GetString("TemplateNotFound_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template not found.
        /// </summary>
        public static string TemplateNotFound_Header {
            get {
                return ResourceManager.GetString("TemplateNotFound_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the template list.
        /// </summary>
        public static string TemplateNotFound_RedirectTitle {
            get {
                return ResourceManager.GetString("TemplateNotFound_RedirectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template saved.
        /// </summary>
        public static string TemplateSavedHeader {
            get {
                return ResourceManager.GetString("TemplateSavedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes have been successfully saved..
        /// </summary>
        public static string TemplateSavedNote {
            get {
                return ResourceManager.GetString("TemplateSavedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template  Title.
        /// </summary>
        public static string TemplateTitle {
            get {
                return ResourceManager.GetString("TemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current month.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current year.
        /// </summary>
        public static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use template.
        /// </summary>
        public static string UseTemplate {
            get {
                return ResourceManager.GetString("UseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View by {!group}.
        /// </summary>
        public static string ViewByDepartments {
            get {
                return ResourceManager.GetString("ViewByDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View by project.
        /// </summary>
        public static string ViewByProjects {
            get {
                return ResourceManager.GetString("ViewByProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View by user.
        /// </summary>
        public static string ViewByUsers {
            get {
                return ResourceManager.GetString("ViewByUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View by user tasks.
        /// </summary>
        public static string ViewByUserTasks {
            get {
                return ResourceManager.GetString("ViewByUserTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show closed milestones.
        /// </summary>
        public static string ViewClosedMilestones {
            get {
                return ResourceManager.GetString("ViewClosedMilestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show closed projects.
        /// </summary>
        public static string ViewClosedProjects {
            get {
                return ResourceManager.GetString("ViewClosedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show report information.
        /// </summary>
        public static string ViewInfo {
            get {
                return ResourceManager.GetString("ViewInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only my projects.
        /// </summary>
        public static string ViewOnlyMyProjecs {
            get {
                return ResourceManager.GetString("ViewOnlyMyProjecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        public static string Weeks2 {
            get {
                return ResourceManager.GetString("Weeks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
