/*
 *
 * (c) Copyright Ascensio System Limited 2010-2015
 *
 * This program is freeware. You can redistribute it and/or modify it under the terms of the GNU 
 * General Public License (GPL) version 3 as published by the Free Software Foundation (https://www.gnu.org/copyleft/gpl.html). 
 * In accordance with Section 7(a) of the GNU GPL its Section 15 shall be amended to the effect that 
 * Ascensio System SIA expressly excludes the warranty of non-infringement of any third-party rights.
 *
 * THIS PROGRAM IS DISTRIBUTED WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF MERCHANTABILITY OR
 * FITNESS FOR A PARTICULAR PURPOSE. For more details, see GNU GPL at https://www.gnu.org/copyleft/gpl.html
 *
 * You can contact Ascensio System SIA by email at sales@onlyoffice.com
 *
 * The interactive user interfaces in modified source and object code versions of ONLYOFFICE must display 
 * Appropriate Legal Notices, as required under Section 5 of the GNU GPL version 3.
 *
 * Pursuant to Section 7 § 3(b) of the GNU GPL you must retain the original ONLYOFFICE logo which contains 
 * relevant author attributions when distributing the software. If the display of the logo in its graphic 
 * form is not reasonably feasible for technical reasons, you must include the words "Powered by ONLYOFFICE" 
 * in every copy of the program you distribute. 
 * Pursuant to Section 7 § 3(e) we decline to grant you any rights under trademark law for use of our trademarks.
 *
*/


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Mail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailApiErrorsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailApiErrorsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Mail.Resources.MailApiErrorsResource", typeof(MailApiErrorsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. Need admin privileges..
        /// </summary>
        internal static string ErrorAccessDenied {
            get {
                return ResourceManager.GetString("ErrorAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This dkim public key is already in use. Please reopen wizard again..
        /// </summary>
        internal static string ErrorDkimPublicKeyInUse {
            get {
                return ResourceManager.GetString("ErrorDkimPublicKeyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to create alias with already existing address..
        /// </summary>
        internal static string ErrorDuplicateAlias {
            get {
                return ResourceManager.GetString("ErrorDuplicateAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain is already in use..
        /// </summary>
        internal static string ErrorDuplicateDomain {
            get {
                return ResourceManager.GetString("ErrorDuplicateDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to create mailgroup with already existing address..
        /// </summary>
        internal static string ErrorDuplicateGroup {
            get {
                return ResourceManager.GetString("ErrorDuplicateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to create mailbox with already existing address..
        /// </summary>
        internal static string ErrorDuplicateMailbox {
            get {
                return ResourceManager.GetString("ErrorDuplicateMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to add already existed address..
        /// </summary>
        internal static string ErrorDuplicateMailGroupAddress {
            get {
                return ResourceManager.GetString("ErrorDuplicateMailGroupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error. Try again later..
        /// </summary>
        internal static string ErrorInternalServer {
            get {
                return ResourceManager.GetString("ErrorInternalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address..
        /// </summary>
        internal static string ErrorInvalidAddress {
            get {
                return ResourceManager.GetString("ErrorInvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid alias name..
        /// </summary>
        internal static string ErrorInvalidAlias {
            get {
                return ResourceManager.GetString("ErrorInvalidAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain name..
        /// </summary>
        internal static string ErrorInvalidDomain {
            get {
                return ResourceManager.GetString("ErrorInvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mailbox name..
        /// </summary>
        internal static string ErrorInvalidMailbox {
            get {
                return ResourceManager.GetString("ErrorInvalidMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect group..
        /// </summary>
        internal static string ErrorInvalidMailGroup {
            get {
                return ResourceManager.GetString("ErrorInvalidMailGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of user&apos;s mailboxes is exceeded..
        /// </summary>
        internal static string ErrorMailboxLimit {
            get {
                return ResourceManager.GetString("ErrorMailboxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown user..
        /// </summary>
        internal static string ErrorUnknownUser {
            get {
                return ResourceManager.GetString("ErrorUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid opearation for shared domain.
        /// </summary>
        internal static string InvalidOpearationForSharedDomain {
            get {
                return ResourceManager.GetString("InvalidOpearationForSharedDomain", resourceCulture);
            }
        }
    }
}
