/*
(c) Copyright Ascensio System SIA 2010-2014

This program is a free software product.
You can redistribute it and/or modify it under the terms 
of the GNU Affero General Public License (AGPL) version 3 as published by the Free Software
Foundation. In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended
to the effect that Ascensio System SIA expressly excludes the warranty of non-infringement of 
any third-party rights.

This program is distributed WITHOUT ANY WARRANTY; without even the implied warranty 
of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For details, see 
the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html

You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.

The  interactive user interfaces in modified source and object code versions of the Program must 
display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
 
Pursuant to Section 7(b) of the License you must retain the original Product logo when 
distributing the program. Pursuant to Section 7(e) we decline to grant you any rights under 
trademark law for use of our trademarks.
 
All the Product's GUI elements, including illustrations and icon sets, as well as technical writing
content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0
International. See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChatResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChatResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Studio.PublicResources.ChatResource", typeof(ChatResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser notifications.
        /// </summary>
        public static string BrowserNotifications {
            get {
                return ResourceManager.GetString("BrowserNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ChatRoomInvite {
            get {
                return ResourceManager.GetString("ChatRoomInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearText {
            get {
                return ResourceManager.GetString("ClearText", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string CloseAllWindows {
            get {
                return ResourceManager.GetString("CloseAllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close item .
        /// </summary>
        public static string CloseItem {
            get {
                return ResourceManager.GetString("CloseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window.
        /// </summary>
        public static string CloseMessageWindowAltTitle {
            get {
                return ResourceManager.GetString("CloseMessageWindowAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat rooms.
        /// </summary>
        public static string ConferenceGroupName {
            get {
                return ResourceManager.GetString("ConferenceGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend chat.
        /// </summary>
        public static string ExtendChatAltTitle {
            get {
                return ResourceManager.GetString("ExtendChatAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string GoTalk {
            get {
                return ResourceManager.GetString("GoTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Ctrl+Enter to send messages.
        /// </summary>
        public static string HintCtrlEnterSender {
            get {
                return ResourceManager.GetString("HintCtrlEnterSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable sounds.
        /// </summary>
        public static string HintSounds {
            get {
                return ResourceManager.GetString("HintSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, input name of chat room:.
        /// </summary>
        public static string InputNameOfChatRoom {
            get {
                return ResourceManager.GetString("InputNameOfChatRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, input name of mailing:.
        /// </summary>
        public static string InputNameOfMailing {
            get {
                return ResourceManager.GetString("InputNameOfMailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your message...
        /// </summary>
        public static string InputNotificationMessage {
            get {
                return ResourceManager.GetString("InputNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailings.
        /// </summary>
        public static string MailingsGroupName {
            get {
                return ResourceManager.GetString("MailingsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string MinimizeAllWindows {
            get {
                return ResourceManager.GetString("MinimizeAllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string MinimizeAllWindowsIfLoseFocus {
            get {
                return ResourceManager.GetString("MinimizeAllWindowsIfLoseFocus", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string MinimizeMessageWindowAltTitle {
            get {
                return ResourceManager.GetString("MinimizeMessageWindowAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message.
        /// </summary>
        public static string NewMessageLabel {
            get {
                return ResourceManager.GetString("NewMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline contacts.
        /// </summary>
        public static string OfflineContacts {
            get {
                return ResourceManager.GetString("OfflineContacts", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string RestoreAllWindows {
            get {
                return ResourceManager.GetString("RestoreAllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string RestoreMessageWindowAltTitle {
            get {
                return ResourceManager.GetString("RestoreMessageWindowAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat and multiple list .
        /// </summary>
        public static string ShowChatFeatureList {
            get {
                return ResourceManager.GetString("ShowChatFeatureList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide chat.
        /// </summary>
        public static string ShowHideChatAltTitle {
            get {
                return ResourceManager.GetString("ShowHideChatAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show invisible dialog windows.
        /// </summary>
        public static string ShowInvisibleWindows {
            get {
                return ResourceManager.GetString("ShowInvisibleWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string SmallChatOptionsAltTitle {
            get {
                return ResourceManager.GetString("SmallChatOptionsAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smileys.
        /// </summary>
        public static string SmileysAltTitle {
            get {
                return ResourceManager.GetString("SmileysAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        public static string StatusAway {
            get {
                return ResourceManager.GetString("StatusAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string StatusNA {
            get {
                return ResourceManager.GetString("StatusNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string StatusOffline {
            get {
                return ResourceManager.GetString("StatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string StatusOnline {
            get {
                return ResourceManager.GetString("StatusOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamLab Chat.
        /// </summary>
        public static string TeamLabChat {
            get {
                return ResourceManager.GetString("TeamLabChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send multiple.
        /// </summary>
        public static string TitleCreateMassSend {
            get {
                return ResourceManager.GetString("TitleCreateMassSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create chat room.
        /// </summary>
        public static string TitleCreateRoom {
            get {
                return ResourceManager.GetString("TitleCreateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string TypingMessage {
            get {
                return ResourceManager.GetString("TypingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
