//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Studio.PublicResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceJS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceJS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Studio.PublicResources.ResourceJS", typeof(ResourceJS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation code field cannot be empty.
        /// </summary>
        public static string ActivateMobilePhoneEmptyCode {
            get {
                return ResourceManager.GetString("ActivateMobilePhoneEmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter mobile phone number.
        /// </summary>
        public static string ActivateMobilePhoneEmptyPhoneNumber {
            get {
                return ResourceManager.GetString("ActivateMobilePhoneEmptyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation code field cannot be empty.
        /// </summary>
        public static string ActivateTfaAppEmptyCode {
            get {
                return ResourceManager.GetString("ActivateTfaAppEmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add filter.
        /// </summary>
        public static string AddFilter {
            get {
                return ResourceManager.GetString("AddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the {0}?{1} and {0}*{1} symbols to perform a single/multiple-character search. For example, to search for all the words beginning with {0}O{1}, use the  {0}O*{1} query. To search for the exact phrase use the quotation marks.{2}Learn more...{3}.
        /// </summary>
        public static string AdvansedFilterInfoText {
            get {
                return ResourceManager.GetString("AdvansedFilterInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending/descending.
        /// </summary>
        public static string AscOrDesc {
            get {
                return ResourceManager.GetString("AscOrDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup copy has been successfully created..
        /// </summary>
        public static string BackupMakeCopySuccess {
            get {
                return ResourceManager.GetString("BackupMakeCopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string BusyStatus {
            get {
                return ResourceManager.GetString("BusyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful purchase of number.
        /// </summary>
        public static string BuyNumberSuccessMsg {
            get {
                return ResourceManager.GetString("BuyNumberSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming call.
        /// </summary>
        public static string CallIncoming {
            get {
                return ResourceManager.GetString("CallIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed call.
        /// </summary>
        public static string CallMissed {
            get {
                return ResourceManager.GetString("CallMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the data you entered will be lost. Are you sure you want to continue?.
        /// </summary>
        public static string CancelConfirmMessage {
            get {
                return ResourceManager.GetString("CancelConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes are applied.
        /// </summary>
        public static string ChangesApplied {
            get {
                return ResourceManager.GetString("ChangesApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes are successfully applied..
        /// </summary>
        public static string ChangesSuccessfullyAppliedMsg {
            get {
                return ResourceManager.GetString("ChangesSuccessfullyAppliedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose owner.
        /// </summary>
        public static string ChooseOwner {
            get {
                return ResourceManager.GetString("ChooseOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose user.
        /// </summary>
        public static string ChooseUser {
            get {
                return ResourceManager.GetString("ChooseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string ClearFilterButton {
            get {
                return ResourceManager.GetString("ClearFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been encountered. Please contact your administrator..
        /// </summary>
        public static string CommonJSErrorMsg {
            get {
                return ResourceManager.GetString("CommonJSErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        public static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new contact.
        /// </summary>
        public static string ContactSelectorAddText {
            get {
                return ResourceManager.GetString("ContactSelectorAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contacts in this list.
        /// </summary>
        public static string ContactSelectorEmptyList {
            get {
                return ResourceManager.GetString("ContactSelectorEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the company title.
        /// </summary>
        public static string ContactSelectorEmptyNameError {
            get {
                return ResourceManager.GetString("ContactSelectorEmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no contacts.
        /// </summary>
        public static string ContactSelectorNoItems {
            get {
                return ResourceManager.GetString("ContactSelectorNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such contact.
        /// </summary>
        public static string ContactSelectorNoResult {
            get {
                return ResourceManager.GetString("ContactSelectorNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such company.
        /// </summary>
        public static string ContactSelectorNotFoundError {
            get {
                return ResourceManager.GetString("ContactSelectorNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while generating report.
        /// </summary>
        public static string CreateReportError {
            get {
                return ResourceManager.GetString("CreateReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment cannot be empty.
        /// </summary>
        public static string EmptyCommentErrorMessage {
            get {
                return ResourceManager.GetString("EmptyCommentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an area for avatar.
        /// </summary>
        public static string EmptySelectedArea {
            get {
                return ResourceManager.GetString("EmptySelectedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email.
        /// </summary>
        public static string ErrorEmptyEmail {
            get {
                return ResourceManager.GetString("ErrorEmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in this field.
        /// </summary>
        public static string ErrorEmptyField {
            get {
                return ResourceManager.GetString("ErrorEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the group title.
        /// </summary>
        public static string ErrorEmptyGroupTitle {
            get {
                return ResourceManager.GetString("ErrorEmptyGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the first name.
        /// </summary>
        public static string ErrorEmptyUserFirstName {
            get {
                return ResourceManager.GetString("ErrorEmptyUserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the last name.
        /// </summary>
        public static string ErrorEmptyUserLastName {
            get {
                return ResourceManager.GetString("ErrorEmptyUserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such group.
        /// </summary>
        public static string ErrorGroupNotExist {
            get {
                return ResourceManager.GetString("ErrorGroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not such person.
        /// </summary>
        public static string ErrorHeadNotExist {
            get {
                return ResourceManager.GetString("ErrorHeadNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid first name.
        /// </summary>
        public static string ErrorInvalidUserFirstName {
            get {
                return ResourceManager.GetString("ErrorInvalidUserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid last name.
        /// </summary>
        public static string ErrorInvalidUserLastName {
            get {
                return ResourceManager.GetString("ErrorInvalidUserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64 chars maximum.
        /// </summary>
        public static string ErrorMesLongField64 {
            get {
                return ResourceManager.GetString("ErrorMesLongField64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date must be later than birth date.
        /// </summary>
        public static string ErrorMessage_InvalidDate {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add the same account and contact twice..
        /// </summary>
        public static string ErrorMessageContactsDuplicated {
            get {
                return ResourceManager.GetString("ErrorMessageContactsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only enter up to 64 characters for this field..
        /// </summary>
        public static string ErrorMessageLongField64 {
            get {
                return ResourceManager.GetString("ErrorMessageLongField64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email.
        /// </summary>
        public static string ErrorNotCorrectEmail {
            get {
                return ResourceManager.GetString("ErrorNotCorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal name is already taken.
        /// </summary>
        public static string ErrorPortalNameExist {
            get {
                return ResourceManager.GetString("ErrorPortalNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed characters in portal name.
        /// </summary>
        public static string ErrorPortalNameIncorrect {
            get {
                return ResourceManager.GetString("ErrorPortalNameIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal name is too short.
        /// </summary>
        public static string ErrorPortalNameTooShort {
            get {
                return ResourceManager.GetString("ErrorPortalNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal name has not been changed.
        /// </summary>
        public static string ErrorPortalNameWasNotChanged {
            get {
                return ResourceManager.GetString("ErrorPortalNameWasNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The users have been successfully added..
        /// </summary>
        public static string FinishImportUserTitle {
            get {
                return ResourceManager.GetString("FinishImportUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greeting ringtones.
        /// </summary>
        public static string GreetingRingtones {
            get {
                return ResourceManager.GetString("GreetingRingtones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} was created successfully..
        /// </summary>
        public static string GroupSelectorAddSuccess {
            get {
                return ResourceManager.GetString("GroupSelectorAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new group.
        /// </summary>
        public static string GroupSelectorAddText {
            get {
                return ResourceManager.GetString("GroupSelectorAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No groups in this list.
        /// </summary>
        public static string GroupSelectorEmptyList {
            get {
                return ResourceManager.GetString("GroupSelectorEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such group.
        /// </summary>
        public static string GroupSelectorNoResults {
            get {
                return ResourceManager.GetString("GroupSelectorNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure that all user fields including first name, last name and email address are filled correctly.
        /// </summary>
        public static string ImportContactsIncorrectFields {
            get {
                return ResourceManager.GetString("ImportContactsIncorrectFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string ImportOf {
            get {
                return ResourceManager.GetString("ImportOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pricing plan does not allow you to add any more users.
        /// </summary>
        public static string ImportUserOverlimitHeader {
            get {
                return ResourceManager.GetString("ImportUserOverlimitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected users will be added as guests. You will be able to change their roles later in the &apos;People&apos; module..
        /// </summary>
        public static string ImportUserOverlimitReason {
            get {
                return ResourceManager.GetString("ImportUserOverlimitReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect IP address format.
        /// </summary>
        public static string IncorrectIPAddressFormatError {
            get {
                return ResourceManager.GetString("IncorrectIPAddressFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string InviteButton {
            get {
                return ResourceManager.GetString("InviteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been successfully updated.
        /// </summary>
        public static string IPRestrictionsSettingsSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("IPRestrictionsSettingsSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty field.
        /// </summary>
        public static string LdapSettingsEmptyField {
            get {
                return ResourceManager.GetString("LdapSettingsEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect port number.
        /// </summary>
        public static string LdapSettingsIncorrectPortNumber {
            get {
                return ResourceManager.GetString("LdapSettingsIncorrectPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to read and agree with the License Agreement.
        /// </summary>
        public static string LicenseAgreementsError {
            get {
                return ResourceManager.GetString("LicenseAgreementsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is not correct.
        /// </summary>
        public static string LicenseKeyError {
            get {
                return ResourceManager.GetString("LicenseKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link has been copied to the clipboard.
        /// </summary>
        public static string LinkCopySuccess {
            get {
                return ResourceManager.GetString("LinkCopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string LoadingDescription {
            get {
                return ResourceManager.GetString("LoadingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait..
        /// </summary>
        public static string LoadingPleaseWait {
            get {
                return ResourceManager.GetString("LoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingProcessing {
            get {
                return ResourceManager.GetString("LoadingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all day.
        /// </summary>
        public static string MailIcsCalendarAllDayEventLabel {
            get {
                return ResourceManager.GetString("MailIcsCalendarAllDayEventLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has been canceled..
        /// </summary>
        public static string MailIcsCancelDescription {
            get {
                return ResourceManager.GetString("MailIcsCancelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event &quot;{0}&quot; has been canceled..
        /// </summary>
        public static string MailIcsCancelDescriptionMerged {
            get {
                return ResourceManager.GetString("MailIcsCancelDescriptionMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled: {0}.
        /// </summary>
        public static string MailIcsCancelSubject {
            get {
                return ResourceManager.GetString("MailIcsCancelSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has been finished..
        /// </summary>
        public static string MailIcsFinishDescription {
            get {
                return ResourceManager.GetString("MailIcsFinishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tentatively accepted the invitation to.
        /// </summary>
        public static string MailIcsReplyMaybeDescription {
            get {
                return ResourceManager.GetString("MailIcsReplyMaybeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} declined the invitation to.
        /// </summary>
        public static string MailIcsReplyNoDescription {
            get {
                return ResourceManager.GetString("MailIcsReplyNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply: {0}.
        /// </summary>
        public static string MailIcsReplySubject {
            get {
                return ResourceManager.GetString("MailIcsReplySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} accepted the invitation to.
        /// </summary>
        public static string MailIcsReplyYesDescription {
            get {
                return ResourceManager.GetString("MailIcsReplyYesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} invites you to.
        /// </summary>
        public static string MailIcsRequestDescription {
            get {
                return ResourceManager.GetString("MailIcsRequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation: {0}.
        /// </summary>
        public static string MailIcsRequestSubject {
            get {
                return ResourceManager.GetString("MailIcsRequestSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string MailIcsRRuleAndLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleAndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approximate.
        /// </summary>
        public static string MailIcsRRuleApproximateLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleApproximateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string MailIcsRRuleAtLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleAtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string MailIcsRRuleDayLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string MailIcsRRuleDaysLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleDaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every.
        /// </summary>
        public static string MailIcsRRuleEveryLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleEveryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string MailIcsRRuleForLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleForLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string MailIcsRRuleHourLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleHourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string MailIcsRRuleHoursLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string MailIcsRRuleInLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        public static string MailIcsRRuleLastLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleLastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string MailIcsRRuleMonthLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string MailIcsRRuleMonthsLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleMonthsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nd.
        /// </summary>
        public static string MailIcsRRuleNdLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleNdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string MailIcsRRuleOnLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on the.
        /// </summary>
        public static string MailIcsRRuleOnTheLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleOnTheLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string MailIcsRRuleOrLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleOrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown format.
        /// </summary>
        public static string MailIcsRRuleParseErrorLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleParseErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rd.
        /// </summary>
        public static string MailIcsRRuleRdLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleRdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st.
        /// </summary>
        public static string MailIcsRRuleStLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleStLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string MailIcsRRuleTheLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleTheLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th.
        /// </summary>
        public static string MailIcsRRuleThLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleThLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string MailIcsRRuleTimeLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        public static string MailIcsRRuleTimesLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleTimesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until.
        /// </summary>
        public static string MailIcsRRuleUntilLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleUntilLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekday.
        /// </summary>
        public static string MailIcsRRuleWeekdayLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleWeekdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekdays.
        /// </summary>
        public static string MailIcsRRuleWeekdaysLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleWeekdaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        public static string MailIcsRRuleWeekLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleWeekLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string MailIcsRRuleWeeksLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleWeeksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string MailIcsRRuleYearLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleYearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string MailIcsRRuleYearsLabel {
            get {
                return ResourceManager.GetString("MailIcsRRuleYearsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has been changed..
        /// </summary>
        public static string MailIcsUpdateDescription {
            get {
                return ResourceManager.GetString("MailIcsUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update: {0}.
        /// </summary>
        public static string MailIcsUpdateSubject {
            get {
                return ResourceManager.GetString("MailIcsUpdateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tentatively accepted the invitation to.
        /// </summary>
        public static string MailIcsYouReplyMaybeDescription {
            get {
                return ResourceManager.GetString("MailIcsYouReplyMaybeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You declined the invitation to.
        /// </summary>
        public static string MailIcsYouReplyNoDescription {
            get {
                return ResourceManager.GetString("MailIcsYouReplyNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You accepted the invitation to.
        /// </summary>
        public static string MailIcsYouReplyYesDescription {
            get {
                return ResourceManager.GetString("MailIcsYouReplyYesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sent the invitation to.
        /// </summary>
        public static string MailIcsYouSentRequestDescription {
            get {
                return ResourceManager.GetString("MailIcsYouSentRequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no subject.
        /// </summary>
        public static string MailNoSubject {
            get {
                return ResourceManager.GetString("MailNoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem has occurred while trying to send this message..
        /// </summary>
        public static string MailSendMessageError {
            get {
                return ResourceManager.GetString("MailSendMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event cancellation notification has been sent to attendees..
        /// </summary>
        public static string MailSentIcalCancelText {
            get {
                return ResourceManager.GetString("MailSentIcalCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been sent to attendees..
        /// </summary>
        public static string MailSentIcalRequestText {
            get {
                return ResourceManager.GetString("MailSentIcalRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your response has been sent to the organizer..
        /// </summary>
        public static string MailSentIcalResponseText {
            get {
                return ResourceManager.GetString("MailSentIcalResponseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message has been sent..
        /// </summary>
        public static string MailSentMessageText {
            get {
                return ResourceManager.GetString("MailSentMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string MeLabel {
            get {
                return ResourceManager.GetString("MeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new milestone.
        /// </summary>
        public static string MilestoneSelectorAddText {
            get {
                return ResourceManager.GetString("MilestoneSelectorAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the due date.
        /// </summary>
        public static string MilestoneSelectorEmptyDueDateError {
            get {
                return ResourceManager.GetString("MilestoneSelectorEmptyDueDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No milestones in this list.
        /// </summary>
        public static string MilestoneSelectorEmptyList {
            get {
                return ResourceManager.GetString("MilestoneSelectorEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the project.
        /// </summary>
        public static string MilestoneSelectorEmptyProjectError {
            get {
                return ResourceManager.GetString("MilestoneSelectorEmptyProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the responsible.
        /// </summary>
        public static string MilestoneSelectorEmptyResponsibleError {
            get {
                return ResourceManager.GetString("MilestoneSelectorEmptyResponsibleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each milestone must have a title.
        /// </summary>
        public static string MilestoneSelectorEmptyTitleError {
            get {
                return ResourceManager.GetString("MilestoneSelectorEmptyTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No milestone in this project.
        /// </summary>
        public static string MilestoneSelectorNoItems {
            get {
                return ResourceManager.GetString("MilestoneSelectorNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such milestone.
        /// </summary>
        public static string MilestoneSelectorNoResult {
            get {
                return ResourceManager.GetString("MilestoneSelectorNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such person.
        /// </summary>
        public static string MilestoneSelectorPersonNotFoundError {
            get {
                return ResourceManager.GetString("MilestoneSelectorPersonNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such project.
        /// </summary>
        public static string MilestoneSelectorProjectNotFoundError {
            get {
                return ResourceManager.GetString("MilestoneSelectorProjectNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Show.
        /// </summary>
        public static string NeverShow {
            get {
                return ResourceManager.GetString("NeverShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not added any templates.
        /// </summary>
        public static string NotAddedAnyTemplates {
            get {
                return ResourceManager.GetString("NotAddedAnyTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string OfflineStatus {
            get {
                return ResourceManager.GetString("OfflineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string OnlineStatus {
            get {
                return ResourceManager.GetString("OnlineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Talk.
        /// </summary>
        public static string OpenTalk {
            get {
                return ResourceManager.GetString("OpenTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while executing the operation..
        /// </summary>
        public static string OperationFailedMsg {
            get {
                return ResourceManager.GetString("OperationFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation has been successfully completed..
        /// </summary>
        public static string OperationSuccededMsg {
            get {
                return ResourceManager.GetString("OperationSuccededMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}You are about to rename your portal.{1}{0}Are you sure you want to continue?{1}.
        /// </summary>
        public static string PortalRenameConfirmationPopup {
            get {
                return ResourceManager.GetString("PortalRenameConfirmationPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal renaming confirmation.
        /// </summary>
        public static string PortalRenameConfirmationTitle {
            get {
                return ResourceManager.GetString("PortalRenameConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project.
        /// </summary>
        public static string ProjectSelectorAddText {
            get {
                return ResourceManager.GetString("ProjectSelectorAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects in this list.
        /// </summary>
        public static string ProjectSelectorEmptyList {
            get {
                return ResourceManager.GetString("ProjectSelectorEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each project must have a manager.
        /// </summary>
        public static string ProjectSelectorEmptyManagerError {
            get {
                return ResourceManager.GetString("ProjectSelectorEmptyManagerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each project must have a title.
        /// </summary>
        public static string ProjectSelectorEmptyTitleError {
            get {
                return ResourceManager.GetString("ProjectSelectorEmptyTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects in this group.
        /// </summary>
        public static string ProjectSelectorNoItems {
            get {
                return ResourceManager.GetString("ProjectSelectorNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such project.
        /// </summary>
        public static string ProjectSelectorNoResult {
            get {
                return ResourceManager.GetString("ProjectSelectorNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such person.
        /// </summary>
        public static string ProjectSelectorNotPersonError {
            get {
                return ResourceManager.GetString("ProjectSelectorNotPersonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue ringtones.
        /// </summary>
        public static string QueueRingtones {
            get {
                return ResourceManager.GetString("QueueRingtones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string RestoreConsumerPath {
            get {
                return ResourceManager.GetString("RestoreConsumerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same restrictions.
        /// </summary>
        public static string SameIPRestrictionError {
            get {
                return ResourceManager.GetString("SameIPRestrictionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings are successfully saved.
        /// </summary>
        public static string SavedTitle {
            get {
                return ResourceManager.GetString("SavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string SelectorCompany {
            get {
                return ResourceManager.GetString("SelectorCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string SelectorCompanyName {
            get {
                return ResourceManager.GetString("SelectorCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact type.
        /// </summary>
        public static string SelectorContactType {
            get {
                return ResourceManager.GetString("SelectorContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string SelectorDueDate {
            get {
                return ResourceManager.GetString("SelectorDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SelectorEmail {
            get {
                return ResourceManager.GetString("SelectorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string SelectorFirstName {
            get {
                return ResourceManager.GetString("SelectorFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string SelectorGroup {
            get {
                return ResourceManager.GetString("SelectorGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string SelectorHead {
            get {
                return ResourceManager.GetString("SelectorHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string SelectorLastName {
            get {
                return ResourceManager.GetString("SelectorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string SelectorManager {
            get {
                return ResourceManager.GetString("SelectorManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones title.
        /// </summary>
        public static string SelectorMilestone {
            get {
                return ResourceManager.GetString("SelectorMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string SelectorPerson {
            get {
                return ResourceManager.GetString("SelectorPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string SelectorProject {
            get {
                return ResourceManager.GetString("SelectorProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string SelectorResponsible {
            get {
                return ResourceManager.GetString("SelectorResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        public static string SelectorSelectedItems {
            get {
                return ResourceManager.GetString("SelectorSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string SelectorTitle {
            get {
                return ResourceManager.GetString("SelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SelectorType {
            get {
                return ResourceManager.GetString("SelectorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string SelectorUser {
            get {
                return ResourceManager.GetString("SelectorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string SelectorVisitor {
            get {
                return ResourceManager.GetString("SelectorVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос успешно отправлен. В ближайшее время с вами свяжется наш менеджер..
        /// </summary>
        public static string SendTariffRequest1 {
            get {
                return ResourceManager.GetString("SendTariffRequest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I created my own web-office. Join me here: {0} #ONLYOFFICE #WebOffice.
        /// </summary>
        public static string ShareInviteLinkDscr {
            get {
                return ResourceManager.GetString("ShareInviteLinkDscr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Next.
        /// </summary>
        public static string ShowNext {
            get {
                return ResourceManager.GetString("ShowNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start filter.
        /// </summary>
        public static string StartFilter {
            get {
                return ResourceManager.GetString("StartFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключить.
        /// </summary>
        public static string StorageButtonEnable {
            get {
                return ResourceManager.GetString("StorageButtonEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        public static string StorageButtonResetToDefault {
            get {
                return ResourceManager.GetString("StorageButtonResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки CDN.
        /// </summary>
        public static string StorageCdnTitle {
            get {
                return ResourceManager.GetString("StorageCdnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки хранилища.
        /// </summary>
        public static string StorageStorageTitle {
            get {
                return ResourceManager.GetString("StorageStorageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} user(s) were successfully added to the portal.
        /// </summary>
        public static string SuccessfullyImportCountUsers {
            get {
                return ResourceManager.GetString("SuccessfullyImportCountUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been successfully updated.
        /// </summary>
        public static string SuccessfullySaveSettingsMessage {
            get {
                return ResourceManager.GetString("SuccessfullySaveSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template not found.
        /// </summary>
        public static string TemplateNotFound {
            get {
                return ResourceManager.GetString("TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to Tips&amp;Tricks.
        /// </summary>
        public static string TipsAndTricksSubscribeBtn {
            get {
                return ResourceManager.GetString("TipsAndTricksSubscribeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe from Tips&amp;Tricks.
        /// </summary>
        public static string TipsAndTricksUnsubscribeBtn {
            get {
                return ResourceManager.GetString("TipsAndTricksUnsubscribeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to unsubscribe from all notifications of the &quot;{0}&quot; module. Are you sure you want to continue?.
        /// </summary>
        public static string UnsubscribeProductMessage {
            get {
                return ResourceManager.GetString("UnsubscribeProductMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension error.
        /// </summary>
        public static string UploadHttpsFileTypeError {
            get {
                return ResourceManager.GetString("UploadHttpsFileTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file.
        /// </summary>
        public static string UploadVoipRingtoneEmptyFileErrorMsg {
            get {
                return ResourceManager.GetString("UploadVoipRingtoneEmptyFileErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uploading file.
        /// </summary>
        public static string UploadVoipRingtoneFileErrorMsg {
            get {
                return ResourceManager.GetString("UploadVoipRingtoneFileErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported file format: mp3.
        /// </summary>
        public static string UploadVoipRingtoneFileFormatErrorMsg {
            get {
                return ResourceManager.GetString("UploadVoipRingtoneFileFormatErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size cannot exceed 5MB .
        /// </summary>
        public static string UploadVoipRingtoneFileSizeErrorMsg {
            get {
                return ResourceManager.GetString("UploadVoipRingtoneFileSizeErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending.
        /// </summary>
        public static string UserPending {
            get {
                return ResourceManager.GetString("UserPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile for {0} was created successfully.
        /// </summary>
        public static string UserSelectorAddSuccess {
            get {
                return ResourceManager.GetString("UserSelectorAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new profile.
        /// </summary>
        public static string UserSelectorAddText {
            get {
                return ResourceManager.GetString("UserSelectorAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users in this list.
        /// </summary>
        public static string UserSelectorEmptyList {
            get {
                return ResourceManager.GetString("UserSelectorEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeds the number of maximum active users.
        /// </summary>
        public static string UserSelectorErrorLimitUsers {
            get {
                return ResourceManager.GetString("UserSelectorErrorLimitUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No groups have been created at the portal so far. Go to the People module to group users..
        /// </summary>
        public static string UserSelectorNoGroups {
            get {
                return ResourceManager.GetString("UserSelectorNoGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users in this group.
        /// </summary>
        public static string UserSelectorNoItems {
            get {
                return ResourceManager.GetString("UserSelectorNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such user.
        /// </summary>
        public static string UserSelectorNoResults {
            get {
                return ResourceManager.GetString("UserSelectorNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice mail ringtones.
        /// </summary>
        public static string VoicemailRingtones {
            get {
                return ResourceManager.GetString("VoicemailRingtones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting ringtones.
        /// </summary>
        public static string WaitingRingtones {
            get {
                return ResourceManager.GetString("WaitingRingtones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you leave now all the entered or unsaved data will be lost..
        /// </summary>
        public static string WarningMessageBeforeUnload {
            get {
                return ResourceManager.GetString("WarningMessageBeforeUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}This means that you can: {1}view portal content open for all portal users,{2}leave comments,{3}attach and download files.{4}.
        /// </summary>
        public static string WelcomeCollaboratorCan {
            get {
                return ResourceManager.GetString("WelcomeCollaboratorCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case you need some additional rights please contact your portal administrator..
        /// </summary>
        public static string WelcomeCollaboratorOtherActions {
            get {
                return ResourceManager.GetString("WelcomeCollaboratorOtherActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ONLYOFFICE.
        /// </summary>
        public static string WelcomeCollaboratorPopupHeader {
            get {
                return ResourceManager.GetString("WelcomeCollaboratorPopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The portal administrator invited you as guest user to the portal..
        /// </summary>
        public static string WelcomeCollaboratorRole {
            get {
                return ResourceManager.GetString("WelcomeCollaboratorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start work.
        /// </summary>
        public static string WelcomeCollaboratorStartWork {
            get {
                return ResourceManager.GetString("WelcomeCollaboratorStartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ONLYOFFICE!.
        /// </summary>
        public static string WelcomeToTeamlab {
            get {
                return ResourceManager.GetString("WelcomeToTeamlab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t set up any password. You will be able to do it later using the &apos;Forgot your password?&apos; link at the portal login page. Are you sure you want to continue?.
        /// </summary>
        public static string WizardCancelConfirmMessage {
            get {
                return ResourceManager.GetString("WizardCancelConfirmMessage", resourceCulture);
            }
        }
    }
}
