//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Studio.Core.Users {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NamingPeopleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamingPeopleResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Studio.Core.Users.NamingPeopleResource", typeof(NamingPeopleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Users.
        /// </summary>
        public static string CommonAddUsers {
            get {
                return ResourceManager.GetString("CommonAddUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string CommonGroup {
            get {
                return ResourceManager.GetString("CommonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string CommonGroupHead {
            get {
                return ResourceManager.GetString("CommonGroupHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string CommonGroups {
            get {
                return ResourceManager.GetString("CommonGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string CommonGuest {
            get {
                return ResourceManager.GetString("CommonGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        public static string CommonGuests {
            get {
                return ResourceManager.GetString("CommonGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string CommonRegDate {
            get {
                return ResourceManager.GetString("CommonRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string CommonSchemaName {
            get {
                return ResourceManager.GetString("CommonSchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string CommonUser {
            get {
                return ResourceManager.GetString("CommonUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string CommonUsers {
            get {
                return ResourceManager.GetString("CommonUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string CommonUserTitle {
            get {
                return ResourceManager.GetString("CommonUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employees.
        /// </summary>
        public static string DefaultAddUsers {
            get {
                return ResourceManager.GetString("DefaultAddUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DefaultGroup {
            get {
                return ResourceManager.GetString("DefaultGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string DefaultGroupHead {
            get {
                return ResourceManager.GetString("DefaultGroupHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string DefaultGroups {
            get {
                return ResourceManager.GetString("DefaultGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string DefaultGuest {
            get {
                return ResourceManager.GetString("DefaultGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        public static string DefaultGuests {
            get {
                return ResourceManager.GetString("DefaultGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employed since.
        /// </summary>
        public static string DefaultRegDate {
            get {
                return ResourceManager.GetString("DefaultRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate.
        /// </summary>
        public static string DefaultSchemaName {
            get {
                return ResourceManager.GetString("DefaultSchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string DefaultUser {
            get {
                return ResourceManager.GetString("DefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string DefaultUsers {
            get {
                return ResourceManager.GetString("DefaultUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string DefaultUserTitle {
            get {
                return ResourceManager.GetString("DefaultUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Teachers/Students.
        /// </summary>
        public static string EducationAddUsers {
            get {
                return ResourceManager.GetString("EducationAddUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string EducationGroup {
            get {
                return ResourceManager.GetString("EducationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Lead.
        /// </summary>
        public static string EducationGroupHead {
            get {
                return ResourceManager.GetString("EducationGroupHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string EducationGroups {
            get {
                return ResourceManager.GetString("EducationGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string EducationGuest {
            get {
                return ResourceManager.GetString("EducationGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        public static string EducationGuests {
            get {
                return ResourceManager.GetString("EducationGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string EducationRegDate {
            get {
                return ResourceManager.GetString("EducationRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Institution.
        /// </summary>
        public static string EducationSchemaName {
            get {
                return ResourceManager.GetString("EducationSchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher/Student.
        /// </summary>
        public static string EducationUser {
            get {
                return ResourceManager.GetString("EducationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers/Students.
        /// </summary>
        public static string EducationUsers {
            get {
                return ResourceManager.GetString("EducationUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string EducationUserTitle {
            get {
                return ResourceManager.GetString("EducationUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;item&gt;
        ///    &lt;id&gt;Common&lt;/id&gt;
        ///    &lt;names&gt;
        ///      &lt;schemaname&gt;CommonSchemaName&lt;/schemaname&gt;
        ///      &lt;user&gt;CommonUser&lt;/user&gt;
        ///      &lt;users&gt;CommonUsers&lt;/users&gt;
        ///      &lt;group&gt;CommonGroup&lt;/group&gt;
        ///      &lt;groups&gt;CommonGroups&lt;/groups&gt;
        ///      &lt;userpost&gt;CommonUserTitle&lt;/userpost&gt;
        ///      &lt;grouphead&gt;CommonGroupHead&lt;/grouphead&gt;
        ///      &lt;regdate&gt;CommonRegDate&lt;/regdate&gt;
        ///      &lt;addusers&gt;CommonAddUsers&lt;/addusers&gt;
        ///      &lt;guest&gt;CommonGuest&lt;/guest&gt;
        ///      &lt;guests&gt;CommonGuests&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PeopleNames {
            get {
                return ResourceManager.GetString("PeopleNames", resourceCulture);
            }
        }
    }
}
