/*
(c) Copyright Ascensio System SIA 2010-2014

This program is a free software product.
You can redistribute it and/or modify it under the terms 
of the GNU Affero General Public License (AGPL) version 3 as published by the Free Software
Foundation. In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended
to the effect that Ascensio System SIA expressly excludes the warranty of non-infringement of 
any third-party rights.

This program is distributed WITHOUT ANY WARRANTY; without even the implied warranty 
of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For details, see 
the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html

You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.

The  interactive user interfaces in modified source and object code versions of the Program must 
display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
 
Pursuant to Section 7(b) of the License you must retain the original Product logo when 
distributing the program. Pursuant to Section 7(e) we decline to grant you any rights under 
trademark law for use of our trademarks.
 
All the Product's GUI elements, including illustrations and icon sets, as well as technical writing
content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0
International. See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Studio.Core.Users {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NamingPeopleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamingPeopleResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Studio.Core.Users.NamingPeopleResource", typeof(NamingPeopleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Members.
        /// </summary>
        public static string CommonAddUsers {
            get {
                return ResourceManager.GetString("CommonAddUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string CommonGroup {
            get {
                return ResourceManager.GetString("CommonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string CommonGroupHead {
            get {
                return ResourceManager.GetString("CommonGroupHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string CommonGroups {
            get {
                return ResourceManager.GetString("CommonGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string CommonGuest {
            get {
                return ResourceManager.GetString("CommonGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        public static string CommonGuests {
            get {
                return ResourceManager.GetString("CommonGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string CommonRegDate {
            get {
                return ResourceManager.GetString("CommonRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string CommonSchemaName {
            get {
                return ResourceManager.GetString("CommonSchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string CommonUser {
            get {
                return ResourceManager.GetString("CommonUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string CommonUsers {
            get {
                return ResourceManager.GetString("CommonUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string CommonUserTitle {
            get {
                return ResourceManager.GetString("CommonUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employees.
        /// </summary>
        public static string DefaultAddUsers {
            get {
                return ResourceManager.GetString("DefaultAddUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DefaultGroup {
            get {
                return ResourceManager.GetString("DefaultGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string DefaultGroupHead {
            get {
                return ResourceManager.GetString("DefaultGroupHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string DefaultGroups {
            get {
                return ResourceManager.GetString("DefaultGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string DefaultGuest {
            get {
                return ResourceManager.GetString("DefaultGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        public static string DefaultGuests {
            get {
                return ResourceManager.GetString("DefaultGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employed since.
        /// </summary>
        public static string DefaultRegDate {
            get {
                return ResourceManager.GetString("DefaultRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate.
        /// </summary>
        public static string DefaultSchemaName {
            get {
                return ResourceManager.GetString("DefaultSchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string DefaultUser {
            get {
                return ResourceManager.GetString("DefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string DefaultUsers {
            get {
                return ResourceManager.GetString("DefaultUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string DefaultUserTitle {
            get {
                return ResourceManager.GetString("DefaultUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;item&gt;
        ///    &lt;id&gt;Common&lt;/id&gt;
        ///    &lt;names&gt;
        ///      &lt;schemaname&gt;CommonSchemaName&lt;/schemaname&gt;
        ///      &lt;user&gt;CommonUser&lt;/user&gt;
        ///      &lt;users&gt;CommonUsers&lt;/users&gt;
        ///      &lt;group&gt;CommonGroup&lt;/group&gt;
        ///      &lt;groups&gt;CommonGroups&lt;/groups&gt;
        ///      &lt;userpost&gt;CommonUserTitle&lt;/userpost&gt;
        ///      &lt;grouphead&gt;CommonGroupHead&lt;/grouphead&gt;
        ///      &lt;regdate&gt;CommonRegDate&lt;/regdate&gt;
        ///      &lt;addusers&gt;CommonAddUsers&lt;/addusers&gt;
        ///      &lt;guest&gt;CommonGuest&lt;/guest&gt;
        ///      &lt;guests&gt;CommonGuests&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PeopleNames {
            get {
                return ResourceManager.GetString("PeopleNames", resourceCulture);
            }
        }
    }
}
