insert into mail_imap_special_mailbox(server, name, folder_id, skip) values
('mail.rambler.ru', 'DraftBox', 3, 1),
('mail.rambler.ru', 'SentBox',  2, 0),
('mail.rambler.ru', 'Spam',     5, 0),
('mail.rambler.ru', 'Trash',    4, 1),
('imap.rambler.ru', 'DraftBox', 3, 1),
('imap.rambler.ru', 'SentBox',  2, 0),
('imap.rambler.ru', 'Spam',     5, 0),
('imap.rambler.ru', 'Trash',    4, 1),
('secureimap.t-online.de', 'INBOX.Drafts', 3, 1),
('secureimap.t-online.de', 'INBOX.Sent', 2, 0),
('secureimap.t-online.de', 'INBOX.Trash', 4, 1),
('secureimap.t-online.de', 'INBOX.Archive', 0, 1),
('imap.googlemail.com', '[Gmail]/Important',0, 1),
('imap.googlemail.com', '[Gmail]/Важное',0, 1),
('imap.googlemail.com', '[Gmail]/Destacados',0, 1),
('imap.googlemail.com', '[Gmail]/Wichtig',0, 1),
('imap.googlemail.com', '[Gmail]/Sent Mail',2, 0),
('imap.googlemail.com', '[Gmail]/Отправленные',2, 0),
('imap.googlemail.com', '[Gmail]/Enviados',2, 0),
('imap.googlemail.com', '[Gmail]/Gesendet',2, 0)
