1. Создать клон таблицы mail_mail без данных

2. ALTER TABLE `mail_mail_copy`
	ADD COLUMN `is_text_body_only` INT(11) NOT NULL DEFAULT '0' AFTER `is_from_tl`;
	
3. INSERT INTO mail_mail_copy (`id`,
	`id_mailbox`,
	`id_user`,
	`tenant`,
	`uidl`,
	`md5`,
	`address`,
	`from_text`,
	`to_text`,
	`reply_to`,
	`cc`,
	`bcc`,
	`subject`,
	`introduction`,
	`importance`,
	`date_received`,
	`date_sent`,
	`size`,
	`attachments_count`,
	`unread`,
	`is_answered`,
	`is_forwarded`,
	`is_from_crm`,
	`is_from_tl`,
	`stream`,
	`folder`,
	`folder_restore`,
	`spam`,
	`time_modified`,
	`is_removed`,
	`mime_message_id`,
	`mime_in_reply_to`,
	`chain_id`,
	`chain_date`)
	SELECT 
	`id`,
	`id_mailbox`,
	`id_user`,
	`tenant`,
	`uidl`,
	`md5`,
	`address`,
	`from_text`,
	`to_text`,
	`reply_to`,
	`cc`,
	`bcc`,
	`subject`,
	`introduction`,
	`importance`,
	`date_received`,
	`date_sent`,
	`size`,
	`attachments_count`,
	`unread`,
	`is_answered`,
	`is_forwarded`,
	`is_from_crm`,
	`is_from_tl`,
	`stream`,
	`folder`,
	`folder_restore`,
	`spam`,
	`time_modified`,
	`is_removed`,
	`mime_message_id`,
	`mime_in_reply_to`,
	`chain_id`,
	`chain_date`
	FROM mail_mail;

4. Переименовать mail_mail в mail_mail_old
5. Переименовать mail_mail_copy в mail_mail
6. Удалить mail_mail_old