/*
 * 
 * (c) Copyright Ascensio System SIA 2010-2014
 * 
 * This program is a free software product.
 * You can redistribute it and/or modify it under the terms of the GNU Affero General Public License
 * (AGPL) version 3 as published by the Free Software Foundation. 
 * In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended to the effect 
 * that Ascensio System SIA expressly excludes the warranty of non-infringement of any third-party rights.
 * 
 * This program is distributed WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * For details, see the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
 * 
 * You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.
 * 
 * The interactive user interfaces in modified source and object code versions of the Program 
 * must display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
 * 
 * Pursuant to Section 7(b) of the License you must retain the original Product logo when distributing the program. 
 * Pursuant to Section 7(e) we decline to grant you any rights under trademark law for use of our trademarks.
 * 
 * All the Product's GUI elements, including illustrations and icon sets, as well as technical 
 * writing content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0 International. 
 * See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
 * 
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Community.News.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Community.News.Resources.NewsResource", typeof(NewsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add News.
        /// </summary>
        public static string Action_Add_Name {
            get {
                return ResourceManager.GetString("Action_Add_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Comment.
        /// </summary>
        public static string Action_Comment_Name {
            get {
                return ResourceManager.GetString("Action_Comment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit comment.
        /// </summary>
        public static string Action_CommentEdit_Name {
            get {
                return ResourceManager.GetString("Action_CommentEdit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit news.
        /// </summary>
        public static string Action_Edit_Name {
            get {
                return ResourceManager.GetString("Action_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit news categories.
        /// </summary>
        public static string Action_EditCategories_Name {
            get {
                return ResourceManager.GetString("Action_EditCategories_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add type.
        /// </summary>
        public static string AddNewType {
            get {
                return ResourceManager.GetString("AddNewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest corporate news, announcements and polls.
        /// </summary>
        public static string AddonDescriptionResourceKey {
            get {
                return ResourceManager.GetString("AddonDescriptionResourceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string AddonName {
            get {
                return ResourceManager.GetString("AddonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AuthCategory_Edit_Name {
            get {
                return ResourceManager.GetString("AuthCategory_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackLink {
            get {
                return ResourceManager.GetString("BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this event?.
        /// </summary>
        public static string ConfirmRemoveMessage {
            get {
                return ResourceManager.GetString("ConfirmRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateColumn {
            get {
                return ResourceManager.GetString("DateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the first announcement.
        /// </summary>
        public static string EmptyScreenAdvertLink {
            get {
                return ResourceManager.GetString("EmptyScreenAdvertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No announcements have been added yet.
        /// </summary>
        public static string EmptyScreenAdvertsCaption {
            get {
                return ResourceManager.GetString("EmptyScreenAdvertsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the first event.
        /// </summary>
        public static string EmptyScreenEventLink {
            get {
                return ResourceManager.GetString("EmptyScreenEventLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No events have been added yet.
        /// </summary>
        public static string EmptyScreenEventsCaption {
            get {
                return ResourceManager.GetString("EmptyScreenEventsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news have been added yet.
        /// </summary>
        public static string EmptyScreenNewsCaption {
            get {
                return ResourceManager.GetString("EmptyScreenNewsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the first news.
        /// </summary>
        public static string EmptyScreenNewsLink {
            get {
                return ResourceManager.GetString("EmptyScreenNewsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the first order.
        /// </summary>
        public static string EmptyScreenOrderLink {
            get {
                return ResourceManager.GetString("EmptyScreenOrderLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No orders have been added yet.
        /// </summary>
        public static string EmptyScreenOrdersCaption {
            get {
                return ResourceManager.GetString("EmptyScreenOrdersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the first poll.
        /// </summary>
        public static string EmptyScreenPollLink {
            get {
                return ResourceManager.GetString("EmptyScreenPollLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No polls have been added yet.
        /// </summary>
        public static string EmptyScreenPollsCaption {
            get {
                return ResourceManager.GetString("EmptyScreenPollsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string EmptyScreenText {
            get {
                return ResourceManager.GetString("EmptyScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string ErrorAccessDenied {
            get {
                return ResourceManager.GetString("ErrorAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your poll question.
        /// </summary>
        public static string ErrorEmptyQuestion {
            get {
                return ResourceManager.GetString("ErrorEmptyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid value.
        /// </summary>
        public static string ErrorNotCorrectMaxNewsSettings {
            get {
                return ResourceManager.GetString("ErrorNotCorrectMaxNewsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter at least two poll choices.
        /// </summary>
        public static string ErrorPollVariantCount {
            get {
                return ResourceManager.GetString("ErrorPollVariantCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event has been deleted.
        /// </summary>
        public static string FeedDeleted {
            get {
                return ResourceManager.GetString("FeedDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string FeedPrevCaption {
            get {
                return ResourceManager.GetString("FeedPrevCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string FeedTypeNews {
            get {
                return ResourceManager.GetString("FeedTypeNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polls.
        /// </summary>
        public static string FeedTypePoll {
            get {
                return ResourceManager.GetString("FeedTypePoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string HideButton {
            get {
                return ResourceManager.GetString("HideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of events to display (1 to 30).
        /// </summary>
        public static string MaxNewsCountSettingsTitle {
            get {
                return ResourceManager.GetString("MaxNewsCountSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate feeds.
        /// </summary>
        public static string ModuleDescription {
            get {
                return ResourceManager.GetString("ModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string NameColumn {
            get {
                return ResourceManager.GetString("NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new event.
        /// </summary>
        public static string NewsAdd {
            get {
                return ResourceManager.GetString("NewsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Event.
        /// </summary>
        public static string NewsAddBreadCrumbsNews {
            get {
                return ResourceManager.GetString("NewsAddBreadCrumbsNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Poll.
        /// </summary>
        public static string NewsAddBreadCrumbsPoll {
            get {
                return ResourceManager.GetString("NewsAddBreadCrumbsPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string NewsAddType {
            get {
                return ResourceManager.GetString("NewsAddType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        public static string NewsAnnouncementsTypeName {
            get {
                return ResourceManager.GetString("NewsAnnouncementsTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string NewsBody {
            get {
                return ResourceManager.GetString("NewsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Events.
        /// </summary>
        public static string NewsBreadCrumbs {
            get {
                return ResourceManager.GetString("NewsBreadCrumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string NewsCaption {
            get {
                return ResourceManager.GetString("NewsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32x_orders.png.
        /// </summary>
        public static string NewsDefaultTypeLogo {
            get {
                return ResourceManager.GetString("NewsDefaultTypeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Event.
        /// </summary>
        public static string NewsEditBreadCrumbsNews {
            get {
                return ResourceManager.GetString("NewsEditBreadCrumbsNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Poll.
        /// </summary>
        public static string NewsEditBreadCrumbsPoll {
            get {
                return ResourceManager.GetString("NewsEditBreadCrumbsPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32x_orders.png.
        /// </summary>
        public static string NewsOrdersTypeLogo {
            get {
                return ResourceManager.GetString("NewsOrdersTypeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string NewsOrdersTypeName {
            get {
                return ResourceManager.GetString("NewsOrdersTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        public static string NewsType {
            get {
                return ResourceManager.GetString("NewsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows the latest events.
        /// </summary>
        public static string NewsWidgetDescription {
            get {
                return ResourceManager.GetString("NewsWidgetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string NewsWidgetName {
            get {
                return ResourceManager.GetString("NewsWidgetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string NewTypeLogo {
            get {
                return ResourceManager.GetString("NewTypeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string NewTypeName {
            get {
                return ResourceManager.GetString("NewTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to {0}Add new event{1}.
        /// </summary>
        public static string NoFeedWidgetMessage {
            get {
                return ResourceManager.GetString("NoFeedWidgetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to {0}Add new poll{1}.
        /// </summary>
        public static string NoPollWidgetMessage {
            get {
                return ResourceManager.GetString("NoPollWidgetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing has been found..
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify about new comments.
        /// </summary>
        public static string NotificationOnNewComments {
            get {
                return ResourceManager.GetString("NotificationOnNewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events Subscriptions.
        /// </summary>
        public static string NotifyOnNewFeed {
            get {
                return ResourceManager.GetString("NotifyOnNewFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to events.
        /// </summary>
        public static string NotifyOnUploadsMessage {
            get {
                return ResourceManager.GetString("NotifyOnUploadsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PleaseWaitMessage {
            get {
                return ResourceManager.GetString("PleaseWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new poll.
        /// </summary>
        public static string PollAdd {
            get {
                return ResourceManager.GetString("PollAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no active polls.
        /// </summary>
        public static string PollListEmpty {
            get {
                return ResourceManager.GetString("PollListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows the latest polls.
        /// </summary>
        public static string PollWidgetDescription {
            get {
                return ResourceManager.GetString("PollWidgetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polls.
        /// </summary>
        public static string PollWidgetName {
            get {
                return ResourceManager.GetString("PollWidgetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string PostButton {
            get {
                return ResourceManager.GetString("PostButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string PostedBy {
            get {
                return ResourceManager.GetString("PostedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Title field is obligatory.
        /// </summary>
        public static string RequaredFieldValidatorCaption {
            get {
                return ResourceManager.GetString("RequaredFieldValidatorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events Search.
        /// </summary>
        public static string SearchDefaultString {
            get {
                return ResourceManager.GetString("SearchDefaultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Events.
        /// </summary>
        public static string SeeAllNews {
            get {
                return ResourceManager.GetString("SeeAllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Polls.
        /// </summary>
        public static string SeeAllPolls {
            get {
                return ResourceManager.GetString("SeeAllPolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on page.
        /// </summary>
        public static string ShowOnPage {
            get {
                return ResourceManager.GetString("ShowOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to comments.
        /// </summary>
        public static string SubscribeOnNewComments {
            get {
                return ResourceManager.GetString("SubscribeOnNewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string TypeNameColumn {
            get {
                return ResourceManager.GetString("TypeNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe from events.
        /// </summary>
        public static string UnNotifyOnUploadsMessage {
            get {
                return ResourceManager.GetString("UnNotifyOnUploadsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe from comments.
        /// </summary>
        public static string UnsubscribeFromNewComments {
            get {
                return ResourceManager.GetString("UnsubscribeFromNewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment added.
        /// </summary>
        public static string UserActivity_AddCommentFeed {
            get {
                return ResourceManager.GetString("UserActivity_AddCommentFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment added.
        /// </summary>
        public static string UserActivity_AddCommentNews {
            get {
                return ResourceManager.GetString("UserActivity_AddCommentNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event added.
        /// </summary>
        public static string UserActivity_AddNewsFeed {
            get {
                return ResourceManager.GetString("UserActivity_AddNewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poll created.
        /// </summary>
        public static string UserActivity_AddPollFeed {
            get {
                return ResourceManager.GetString("UserActivity_AddPollFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment deleted.
        /// </summary>
        public static string UserActivity_DeleteCommentFeed {
            get {
                return ResourceManager.GetString("UserActivity_DeleteCommentFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment deleted.
        /// </summary>
        public static string UserActivity_DeleteCommentNews {
            get {
                return ResourceManager.GetString("UserActivity_DeleteCommentNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event deleted.
        /// </summary>
        public static string UserActivity_DeleteFeed {
            get {
                return ResourceManager.GetString("UserActivity_DeleteFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poll deleted.
        /// </summary>
        public static string UserActivity_DeletePoll {
            get {
                return ResourceManager.GetString("UserActivity_DeletePoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment edited.
        /// </summary>
        public static string UserActivity_EditCommentFeed {
            get {
                return ResourceManager.GetString("UserActivity_EditCommentFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment edited.
        /// </summary>
        public static string UserActivity_EditCommentNews {
            get {
                return ResourceManager.GetString("UserActivity_EditCommentNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event edited.
        /// </summary>
        public static string UserActivity_EditNewsFeed {
            get {
                return ResourceManager.GetString("UserActivity_EditNewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poll edited.
        /// </summary>
        public static string UserActivity_EditPollFeed {
            get {
                return ResourceManager.GetString("UserActivity_EditPollFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vote added.
        /// </summary>
        public static string UserActivity_Vote {
            get {
                return ResourceManager.GetString("UserActivity_Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vote added.
        /// </summary>
        public static string Voted {
            get {
                return ResourceManager.GetString("Voted", resourceCulture);
            }
        }
    }
}
