//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.CRM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CRMDealResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CRMDealResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.CRM.Resources.CRMDealResource", typeof(CRMDealResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new opportunity.
        /// </summary>
        public static string AddNewDeal {
            get {
                return ResourceManager.GetString("AddNewDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Create New Opportunity.
        /// </summary>
        public static string AddThisAndCreateDealButton {
            get {
                return ResourceManager.GetString("AddThisAndCreateDealButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AddThisDealButton {
            get {
                return ResourceManager.GetString("AddThisDealButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Opportunities.
        /// </summary>
        public static string AllDeals {
            get {
                return ResourceManager.GetString("AllDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stake.
        /// </summary>
        public static string BidType {
            get {
                return ResourceManager.GetString("BidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fix.
        /// </summary>
        public static string BidType_FixedBid {
            get {
                return ResourceManager.GetString("BidType_FixedBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per day.
        /// </summary>
        public static string BidType_PerDay {
            get {
                return ResourceManager.GetString("BidType_PerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per hour.
        /// </summary>
        public static string BidType_PerHour {
            get {
                return ResourceManager.GetString("BidType_PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per month.
        /// </summary>
        public static string BidType_PerMonth {
            get {
                return ResourceManager.GetString("BidType_PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per week.
        /// </summary>
        public static string BidType_PerWeek {
            get {
                return ResourceManager.GetString("BidType_PerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per year.
        /// </summary>
        public static string BidType_PerYear {
            get {
                return ResourceManager.GetString("BidType_PerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment recurrence.
        /// </summary>
        public static string BidTypePeriod {
            get {
                return ResourceManager.GetString("BidTypePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string ByStage {
            get {
                return ResourceManager.GetString("ByStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage type.
        /// </summary>
        public static string ByStageType {
            get {
                return ResourceManager.GetString("ByStageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity contact.
        /// </summary>
        public static string ClientDeal {
            get {
                return ResourceManager.GetString("ClientDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the first opportunity.
        /// </summary>
        public static string CreateFirstDeal {
            get {
                return ResourceManager.GetString("CreateFirstDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new opportunity.
        /// </summary>
        public static string CreateNewDeal {
            get {
                return ResourceManager.GetString("CreateNewDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current opportunity.
        /// </summary>
        public static string CurrentDeal {
            get {
                return ResourceManager.GetString("CurrentDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity at stage.
        /// </summary>
        public static string CurrentDealMilestone {
            get {
                return ResourceManager.GetString("CurrentDealMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom period.
        /// </summary>
        public static string CustomDateFilter {
            get {
                return ResourceManager.GetString("CustomDateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other users.
        /// </summary>
        public static string CustomResponsibleFilter {
            get {
                return ResourceManager.GetString("CustomResponsibleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity.
        /// </summary>
        public static string Deal {
            get {
                return ResourceManager.GetString("Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The permissions will be set to the opportunities where you are the author.
        /// </summary>
        public static string DealAccessRightsLimit {
            get {
                return ResourceManager.GetString("DealAccessRightsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string DealAmount {
            get {
                return ResourceManager.GetString("DealAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string DealCount {
            get {
                return ResourceManager.GetString("DealCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Stages.
        /// </summary>
        public static string DealMilestone {
            get {
                return ResourceManager.GetString("DealMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The salesperson takes a series of question and answer sessions in order to identify the requirements of the prospect.
        /// </summary>
        public static string DealMilestone_Champion_Description {
            get {
                return ResourceManager.GetString("DealMilestone_Champion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need assessment.
        /// </summary>
        public static string DealMilestone_Champion_Title {
            get {
                return ResourceManager.GetString("DealMilestone_Champion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A contact with the potential buyer is needed to understand the future sales prospective.
        /// </summary>
        public static string DealMilestone_InitialContact_Description {
            get {
                return ResourceManager.GetString("DealMilestone_InitialContact_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial contact.
        /// </summary>
        public static string DealMilestone_InitialContact_Title {
            get {
                return ResourceManager.GetString("DealMilestone_InitialContact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure. The opportunity is closed due to the lack of perspective.
        /// </summary>
        public static string DealMilestone_Lost_Description {
            get {
                return ResourceManager.GetString("DealMilestone_Lost_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessfully closed.
        /// </summary>
        public static string DealMilestone_Lost_Title {
            get {
                return ResourceManager.GetString("DealMilestone_Lost_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The potential buyer has expressed his interest in the salesperson&apos;s goods or services.
        /// </summary>
        public static string DealMilestone_Opportunity_Description {
            get {
                return ResourceManager.GetString("DealMilestone_Opportunity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualified prospect.
        /// </summary>
        public static string DealMilestone_Opportunity_Title {
            get {
                return ResourceManager.GetString("DealMilestone_Opportunity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The salesperson tries to identify whether the customer can be his/her potential buyer.
        /// </summary>
        public static string DealMilestone_Preapproach_Description {
            get {
                return ResourceManager.GetString("DealMilestone_Preapproach_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application of initial fit criteria.
        /// </summary>
        public static string DealMilestone_Preapproach_Title {
            get {
                return ResourceManager.GetString("DealMilestone_Preapproach_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The potential buyer has received a written offering from the salesperson.
        /// </summary>
        public static string DealMilestone_Prospect_Description {
            get {
                return ResourceManager.GetString("DealMilestone_Prospect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal.
        /// </summary>
        public static string DealMilestone_Prospect_Title {
            get {
                return ResourceManager.GetString("DealMilestone_Prospect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The potential buyer is identified as a person or entity that has the interest and authority to purchase a product or service.
        /// </summary>
        public static string DealMilestone_Suspect_Description {
            get {
                return ResourceManager.GetString("DealMilestone_Suspect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspect.
        /// </summary>
        public static string DealMilestone_Suspect_Title {
            get {
                return ResourceManager.GetString("DealMilestone_Suspect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The potential buyer has already discussed your offering in details.
        /// </summary>
        public static string DealMilestone_Verbal_Description {
            get {
                return ResourceManager.GetString("DealMilestone_Verbal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiations.
        /// </summary>
        public static string DealMilestone_Verbal_Title {
            get {
                return ResourceManager.GetString("DealMilestone_Verbal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deal. The opportunity is closed successfully.
        /// </summary>
        public static string DealMilestone_Won_Description {
            get {
                return ResourceManager.GetString("DealMilestone_Won_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closure/Transaction.
        /// </summary>
        public static string DealMilestone_Won_Title {
            get {
                return ResourceManager.GetString("DealMilestone_Won_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage type.
        /// </summary>
        public static string DealMilestoneType {
            get {
                return ResourceManager.GetString("DealMilestoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Participant.
        /// </summary>
        public static string DealParticipant {
            get {
                return ResourceManager.GetString("DealParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Participants.
        /// </summary>
        public static string DealParticipants {
            get {
                return ResourceManager.GetString("DealParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunities.
        /// </summary>
        public static string Deals {
            get {
                return ResourceManager.GetString("Deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Tag.
        /// </summary>
        public static string DealTag {
            get {
                return ResourceManager.GetString("DealTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Tag List.
        /// </summary>
        public static string DealTagList {
            get {
                return ResourceManager.GetString("DealTagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Tags.
        /// </summary>
        public static string DealTags {
            get {
                return ResourceManager.GetString("DealTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete opportunity.
        /// </summary>
        public static string DeleteDeal {
            get {
                return ResourceManager.GetString("DeleteDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting opportunities.
        /// </summary>
        public static string DeletingDeals {
            get {
                return ResourceManager.GetString("DeletingDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionDeal {
            get {
                return ResourceManager.GetString("DescriptionDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit «{0}» opportunity.
        /// </summary>
        public static string EditDealLabel {
            get {
                return ResourceManager.GetString("EditDealLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit opportunity.
        /// </summary>
        public static string EditThisDealButton {
            get {
                return ResourceManager.GetString("EditThisDealButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunities let you track potential sales to your clients. Determine the {0}opportunity stages{1} in accordance with your business process, keep history, assign tasks, upload documents, calculate profit with every client..
        /// </summary>
        public static string EmptyContentDealsDescribe {
            get {
                return ResourceManager.GetString("EmptyContentDealsDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No opportunities matching your filter can be displayed in this section. Please select other filter options or clear filter to view all the opportunities in this section. Or you can create the opportunity in case it is absent from the list..
        /// </summary>
        public static string EmptyContentDealsFilterDescribe {
            get {
                return ResourceManager.GetString("EmptyContentDealsFilterDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No opportunities to be displayed for this filter here.
        /// </summary>
        public static string EmptyContentDealsFilterHeader {
            get {
                return ResourceManager.GetString("EmptyContentDealsFilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opportunity list is empty.
        /// </summary>
        public static string EmptyContentDealsHeader {
            get {
                return ResourceManager.GetString("EmptyContentDealsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the opportunity title.
        /// </summary>
        public static string EmptyDealName {
            get {
                return ResourceManager.GetString("EmptyDealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every opportunity must have a responsible one.
        /// </summary>
        public static string EmptyDealResponsible {
            get {
                return ResourceManager.GetString("EmptyDealResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The participant list is empty.
        /// </summary>
        public static string EmptyPeopleInDealContent {
            get {
                return ResourceManager.GetString("EmptyPeopleInDealContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add participants to your opportunity from the list of companies or persons. After this is done you will know what contacts are associated with this opportunity and who you can deal with..
        /// </summary>
        public static string EmptyPeopleInDealDescript {
            get {
                return ResourceManager.GetString("EmptyPeopleInDealDescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated/Actual due date.
        /// </summary>
        public static string Estimated {
            get {
                return ResourceManager.GetString("Estimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string ExpectedValue {
            get {
                return ResourceManager.GetString("ExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string FilterByContact {
            get {
                return ResourceManager.GetString("FilterByContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant.
        /// </summary>
        public static string FilterByParticipant {
            get {
                return ResourceManager.GetString("FilterByParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage/stage type.
        /// </summary>
        public static string FilterByStageOrStageType {
            get {
                return ResourceManager.GetString("FilterByStageOrStageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find opportunity by title.
        /// </summary>
        public static string FindDealByName {
            get {
                return ResourceManager.GetString("FindDealByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import opportunities.
        /// </summary>
        public static string ImportDeals {
            get {
                return ResourceManager.GetString("ImportDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A properly formed CSV file should be selected on your computer HDD. It must contain the fields or columns separated by the selected delimiter which will be used to import opportunities. The files containing more than {0} rows should be divided into smaller parts for proper importing. Make sure you selected the portal users who need to be granted access to the information to be imported, otherwise the data from the CSV file will be available to all portal users..
        /// </summary>
        public static string ImportFromCSVStepOneDescription {
            get {
                return ResourceManager.GetString("ImportFromCSVStepOneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a CSV file and set access rights before you import opportunities.
        /// </summary>
        public static string ImportFromCSVStepOneHeader {
            get {
                return ResourceManager.GetString("ImportFromCSVStepOneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match your file columns with the corresponding ONLYOFFICE™ CRM fields. Please pay your attention to the fact that to import opportunities correctly you need to have at least the following columns from your file matched with the fields of the ONLYOFFICE™ CRM: &apos;Opportunity Title&apos;, &apos;Opportunity Responsible&apos;. The fields containing the dates must have the following format: {0}. The currency field must be set in accordance with the international three letter code (e.g. USD, JPY, AUD)..
        /// </summary>
        public static string ImportFromCSVStepTwoDescription {
            get {
                return ResourceManager.GetString("ImportFromCSVStepTwoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, verify the fields.
        /// </summary>
        public static string ImportFromCSVStepTwoHeader {
            get {
                return ResourceManager.GetString("ImportFromCSVStepTwoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to oppotunity list.
        /// </summary>
        public static string ImportStartingPanelButton {
            get {
                return ResourceManager.GetString("ImportStartingPanelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import of  opportunities can take several minutes depending on the amount of your data..
        /// </summary>
        public static string ImportStartingPanelDescription {
            get {
                return ResourceManager.GetString("ImportStartingPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing started.
        /// </summary>
        public static string ImportStartingPanelHeader {
            get {
                return ResourceManager.GetString("ImportStartingPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from existing opportunities or add a new one.
        /// </summary>
        public static string LinkDealsFromExisting {
            get {
                return ResourceManager.GetString("LinkDealsFromExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link or create opportunity.
        /// </summary>
        public static string LinkOrCreateDeal {
            get {
                return ResourceManager.GetString("LinkOrCreateDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My opportunities.
        /// </summary>
        public static string MyDeals {
            get {
                return ResourceManager.GetString("MyDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity title.
        /// </summary>
        public static string NameDeal {
            get {
                return ResourceManager.GetString("NameDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget is not set.
        /// </summary>
        public static string NoExpectedValue {
            get {
                return ResourceManager.GetString("NoExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other opportunity participants.
        /// </summary>
        public static string OtherMembersDeal {
            get {
                return ResourceManager.GetString("OtherMembersDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string Overdue {
            get {
                return ResourceManager.GetString("Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string PeopleInDeal {
            get {
                return ResourceManager.GetString("PeopleInDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict access to the opportunity.
        /// </summary>
        public static string PrivatePanelCheckBoxLabel {
            get {
                return ResourceManager.GetString("PrivatePanelCheckBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success probability.
        /// </summary>
        public static string ProbabilityOfWinning {
            get {
                return ResourceManager.GetString("ProbabilityOfWinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible for the opportunity.
        /// </summary>
        public static string ResponsibleDeal {
            get {
                return ResourceManager.GetString("ResponsibleDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize user fields.
        /// </summary>
        public static string SettingCustomFields {
            get {
                return ResourceManager.GetString("SettingCustomFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to profile.
        /// </summary>
        public static string ShowDealProfile {
            get {
                return ResourceManager.GetString("ShowDealProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in a new tab.
        /// </summary>
        public static string ShowDealProfileNewTab {
            get {
                return ResourceManager.GetString("ShowDealProfileNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show total amount.
        /// </summary>
        public static string ShowTotalAmount {
            get {
                return ResourceManager.GetString("ShowTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Importing.
        /// </summary>
        public static string StartImport {
            get {
                return ResourceManager.GetString("StartImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity stages let you determine steps necessary to complete the deal. The default opportunity stages are approach, discussion, evaluation, negotiation, commitment, success, zero-point. To be able to edit them the portal administrator rights are needed..
        /// </summary>
        public static string TooltipStages {
            get {
                return ResourceManager.GetString("TooltipStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All opportunities.
        /// </summary>
        public static string TotalDeals {
            get {
                return ResourceManager.GetString("TotalDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page total.
        /// </summary>
        public static string TotalOnPage {
            get {
                return ResourceManager.GetString("TotalOnPage", resourceCulture);
            }
        }
    }
}
