/*
 * 
 * (c) Copyright Ascensio System SIA 2010-2014
 * 
 * This program is a free software product.
 * You can redistribute it and/or modify it under the terms of the GNU Affero General Public License
 * (AGPL) version 3 as published by the Free Software Foundation. 
 * In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended to the effect 
 * that Ascensio System SIA expressly excludes the warranty of non-infringement of any third-party rights.
 * 
 * This program is distributed WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * For details, see the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
 * 
 * You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.
 * 
 * The interactive user interfaces in modified source and object code versions of the Program 
 * must display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
 * 
 * Pursuant to Section 7(b) of the License you must retain the original Product logo when distributing the program. 
 * Pursuant to Section 7(e) we decline to grant you any rights under trademark law for use of our trademarks.
 * 
 * All the Product's GUI elements, including illustrations and icon sets, as well as technical 
 * writing content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0 International. 
 * See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
 * 
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.CRM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CRMVoipResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CRMVoipResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.CRM.Resources.CRMVoipResource", typeof(CRMVoipResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string AddOperatorBtn {
            get {
                return ResourceManager.GetString("AddOperatorBtn", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string AddOperatorsBtn {
            get {
                return ResourceManager.GetString("AddOperatorsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string AddRingtoneBtn {
            get {
                return ResourceManager.GetString("AddRingtoneBtn", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string AliasDscrMsg {
            get {
                return ResourceManager.GetString("AliasDscrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string AliasPlaceholder {
            get {
                return ResourceManager.GetString("AliasPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string BuyNumberBtn {
            get {
                return ResourceManager.GetString("BuyNumberBtn", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string BuyNumberHeader {
            get {
                return ResourceManager.GetString("BuyNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string CallAgent {
            get {
                return ResourceManager.GetString("CallAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string CallClient {
            get {
                return ResourceManager.GetString("CallClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string CallCost {
            get {
                return ResourceManager.GetString("CallCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime.
        /// </summary>
        public static string CallDatetime {
            get {
                return ResourceManager.GetString("CallDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string CallDuration {
            get {
                return ResourceManager.GetString("CallDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CallId {
            get {
                return ResourceManager.GetString("CallId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string CallType {
            get {
                return ResourceManager.GetString("CallType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Time.
        /// </summary>
        public static string CallWaitingTime {
            get {
                return ResourceManager.GetString("CallWaitingTime", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string DeleteNumberBtn {
            get {
                return ResourceManager.GetString("DeleteNumberBtn", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string DeleteRingtoneBtn {
            get {
                return ResourceManager.GetString("DeleteRingtoneBtn", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string EditBtn {
            get {
                return ResourceManager.GetString("EditBtn", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string GreetingRingtones {
            get {
                return ResourceManager.GetString("GreetingRingtones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Call.
        /// </summary>
        public static string IncomingCall {
            get {
                return ResourceManager.GetString("IncomingCall", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string IncomingCallsQueueDscrMsg {
            get {
                return ResourceManager.GetString("IncomingCallsQueueDscrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string IncomingCallsQueueSize {
            get {
                return ResourceManager.GetString("IncomingCallsQueueSize", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string LoadingMsg {
            get {
                return ResourceManager.GetString("LoadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string NoAvailableNumbersMsg {
            get {
                return ResourceManager.GetString("NoAvailableNumbersMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string NoExistingNumbersMsg {
            get {
                return ResourceManager.GetString("NoExistingNumbersMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string NoNumbersMsg {
            get {
                return ResourceManager.GetString("NoNumbersMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string NoSearchingNumbersMsg {
            get {
                return ResourceManager.GetString("NoSearchingNumbersMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string NumberOperators {
            get {
                return ResourceManager.GetString("NumberOperators", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string NumbersCountDscrMsg {
            get {
                return ResourceManager.GetString("NumbersCountDscrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string NumbersCountMsg {
            get {
                return ResourceManager.GetString("NumbersCountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string OperatorPause {
            get {
                return ResourceManager.GetString("OperatorPause", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string OperatorPauseDisabled {
            get {
                return ResourceManager.GetString("OperatorPauseDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string OperatorPauseDscrMsg {
            get {
                return ResourceManager.GetString("OperatorPauseDscrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string OperatorPauseEnabled {
            get {
                return ResourceManager.GetString("OperatorPauseEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string OutgoingCalls {
            get {
                return ResourceManager.GetString("OutgoingCalls", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string QueueRingtones {
            get {
                return ResourceManager.GetString("QueueRingtones", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string QuickTuning {
            get {
                return ResourceManager.GetString("QuickTuning", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string QuickTuningDscrMsg {
            get {
                return ResourceManager.GetString("QuickTuningDscrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string RecordingCalls {
            get {
                return ResourceManager.GetString("RecordingCalls", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string RecordingsCallsPlayNotSupportedMsg {
            get {
                return ResourceManager.GetString("RecordingsCallsPlayNotSupportedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string RecordingsCallsPlayNotSupportedTipMsg {
            get {
                return ResourceManager.GetString("RecordingsCallsPlayNotSupportedTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string RingtonesList {
            get {
                return ResourceManager.GetString("RingtonesList", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string RingtonesTuning {
            get {
                return ResourceManager.GetString("RingtonesTuning", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string RingtonesTuningDscrMsg {
            get {
                return ResourceManager.GetString("RingtonesTuningDscrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string RingtonesUploadingRecomendationsMsg {
            get {
                return ResourceManager.GetString("RingtonesUploadingRecomendationsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string TuningNumber {
            get {
                return ResourceManager.GetString("TuningNumber", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string UnspecifiedOption {
            get {
                return ResourceManager.GetString("UnspecifiedOption", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string UpdateSettingsBtn {
            get {
                return ResourceManager.GetString("UpdateSettingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string VirtualNumbers {
            get {
                return ResourceManager.GetString("VirtualNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string VirtualNumbersAndOperators {
            get {
                return ResourceManager.GetString("VirtualNumbersAndOperators", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string VirtualNumbersDscrMsg {
            get {
                return ResourceManager.GetString("VirtualNumbersDscrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string Voicemail {
            get {
                return ResourceManager.GetString("Voicemail", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string VoicemailRingtones {
            get {
                return ResourceManager.GetString("VoicemailRingtones", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string WaitingRingtones {
            get {
                return ResourceManager.GetString("WaitingRingtones", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string WaitingTimeout {
            get {
                return ResourceManager.GetString("WaitingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string WaitingTimeout10Minutes {
            get {
                return ResourceManager.GetString("WaitingTimeout10Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string WaitingTimeout15Minutes {
            get {
                return ResourceManager.GetString("WaitingTimeout15Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string WaitingTimeout5Minutes {
            get {
                return ResourceManager.GetString("WaitingTimeout5Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string WaitingTimeoutDscrMsg {
            get {
                return ResourceManager.GetString("WaitingTimeoutDscrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string WorkingHoursFormatErrorMsg {
            get {
                return ResourceManager.GetString("WorkingHoursFormatErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string WorkingHoursFormatTip {
            get {
                return ResourceManager.GetString("WorkingHoursFormatTip", resourceCulture);
            }
        }
    }
}
