namespace ASC.AuditTrail.Types
{
    public enum ModuleType
    {
        None,
        Files,
        Folders,
        DocumentsSettings,
        Companies,
        Persons,
        Contacts,
        CrmTasks,
        Opportunities,
        Invoices,
        Cases,
        CommonCrmSettings,
        ContactsSettings,
        ContactTypes,
        InvoiceSettings,
        OtherCrmSettings,
        Users,
        Groups,
        Projects,
        Milestones,
        Tasks,
        Discussions,
        TimeTracking,
        Reports,
        ProjectsSettings,
        General,
        Products
    }
}
