/*
 * 
 * (c) Copyright Ascensio System SIA 2010-2014
 * 
 * This program is a free software product.
 * You can redistribute it and/or modify it under the terms of the GNU Affero General Public License
 * (AGPL) version 3 as published by the Free Software Foundation. 
 * In accordance with Section 7(a) of the GNU AGPL its Section 15 shall be amended to the effect 
 * that Ascensio System SIA expressly excludes the warranty of non-infringement of any third-party rights.
 * 
 * This program is distributed WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * For details, see the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
 * 
 * You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia, EU, LV-1021.
 * 
 * The interactive user interfaces in modified source and object code versions of the Program 
 * must display Appropriate Legal Notices, as required under Section 5 of the GNU AGPL version 3.
 * 
 * Pursuant to Section 7(b) of the License you must retain the original Product logo when distributing the program. 
 * Pursuant to Section 7(e) we decline to grant you any rights under trademark law for use of our trademarks.
 * 
 * All the Product's GUI elements, including illustrations and icon sets, as well as technical 
 * writing content are licensed under the terms of the Creative Commons Attribution-ShareAlike 4.0 International. 
 * See the License terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
 * 
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.UserControls.SocialMedia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SocialMediaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SocialMediaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.UserControls.SocialMedia.Resources.SocialMediaResource", typeof(SocialMediaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorFacebookAccountNotFound {
            get {
                return ResourceManager.GetString("ErrorFacebookAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorFacebookAPILimit {
            get {
                return ResourceManager.GetString("ErrorFacebookAPILimit", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorFacebookOAuth {
            get {
                return ResourceManager.GetString("ErrorFacebookOAuth", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorInternalServer {
            get {
                return ResourceManager.GetString("ErrorInternalServer", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorLinkedInUnauthorized {
            get {
                return ResourceManager.GetString("ErrorLinkedInUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorTwitterAccountNotFound {
            get {
                return ResourceManager.GetString("ErrorTwitterAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorTwitterConnectionFailure {
            get {
                return ResourceManager.GetString("ErrorTwitterConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorTwitterIsDown {
            get {
                return ResourceManager.GetString("ErrorTwitterIsDown", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorTwitterRateLimit {
            get {
                return ResourceManager.GetString("ErrorTwitterRateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorTwitterUnauthorized {
            get {
                return ResourceManager.GetString("ErrorTwitterUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string ErrorUnknownTwitterAccount {
            get {
                return ResourceManager.GetString("ErrorUnknownTwitterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string MessageCount {
            get {
                return ResourceManager.GetString("MessageCount", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string SocialMediaAccountNotFound {
            get {
                return ResourceManager.GetString("SocialMediaAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string SocialMediaAccountNotFoundFacebook {
            get {
                return ResourceManager.GetString("SocialMediaAccountNotFoundFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string SocialMediaAccountNotFoundLinkedIn {
            get {
                return ResourceManager.GetString("SocialMediaAccountNotFoundLinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        
        /// </summary>
        public static string SocialMediaAccountNotFoundTwitter {
            get {
                return ResourceManager.GetString("SocialMediaAccountNotFoundTwitter", resourceCulture);
            }
        }
    }
}
